# Generated by Django 5.2.1 on 2025-06-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0002_hotelinfo_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='info_qr_board',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='info_qr_dining',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='info_qr_kids',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='info_qr_offers',
            field=models.URLField(blank=True, null=True),
        ),
    ]
