# Generated by Django 5.2.1 on 2025-06-09 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0003_hotelinfo_info_qr_board_hotelinfo_info_qr_dining_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelInfoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Internal identifier (e.g. 'kid_entertainment')", unique=True)),
                ('name', models.CharField(help_text="Human‐readable name (e.g. 'Kid Entertainment')", max_length=200)),
            ],
            options={
                'verbose_name': 'Hotel Info Category',
                'verbose_name_plural': 'Hotel Info Categories',
            },
        ),
        migrations.RenameField(
            model_name='hotelinfo',
            old_name='info_qr_board',
            new_name='info_qr',
        ),
        migrations.RemoveField(
            model_name='hotelinfo',
            name='info_qr_dining',
        ),
        migrations.RemoveField(
            model_name='hotelinfo',
            name='info_qr_kids',
        ),
        migrations.RemoveField(
            model_name='hotelinfo',
            name='info_qr_offers',
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infos', to='hotel_info.hotelinfocategory'),
        ),
    ]
