# Generated by Django 5.2.1 on 2025-06-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0004_hotelinfocategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='event_date',
            field=models.DateField(blank=True, help_text='Date of the event (optional)', null=True),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='event_time',
            field=models.TimeField(blank=True, help_text='Time of the event (optional)', null=True),
        ),
    ]
