# Generated by Django 5.2.1 on 2025-06-09 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_subdomain_alter_hotel_slug'),
        ('hotel_info', '0005_hotelinfo_event_date_hotelinfo_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelinfo',
            name='info_qr',
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CategoryQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_url', models.URLField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='hotel_info.hotelinfocategory')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_qrcodes', to='hotel.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'category')},
            },
        ),
    ]
