# Generated by Django 5.2.1 on 2025-06-10 11:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0006_remove_hotelinfo_info_qr_alter_hotelinfo_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
