# Generated by Django 5.2.1 on 2025-07-03 20:01

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_logo'),
        ('hotel_info', '0007_hotelinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinfo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='hotel_info.hotelinfocategory'),
        ),
        migrations.CreateModel(
            name='GoodToKnowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Slug for QR access (e.g. 'wifi-password')")),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('qr_url', models.URLField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_info', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_to_know_entries', to='hotel.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'slug')},
            },
        ),
    ]
