# Generated by Django 5.2.1 on 2025-06-17 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0007_hotelinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinfo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='hotel_info.hotelinfocategory'),
        ),
    ]
