# Generated by Django 5.2.4 on 2025-08-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0008_alter_hotelinfo_category_goodtoknowentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
