# Generated by Django 5.2.1 on 2025-05-22 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakfastItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='breakfast_items/')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Mains', 'Mains'), ('Breads', 'Breads'), ('Drinks', 'Drinks'), ('Sides', 'Sides')], default='Mains', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BreakfastOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_service_items/')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Starters', 'Starters'), ('Mains', 'Mains'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks'), ('Others', 'Others')], default='Others', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BreakfastOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_services.breakfastitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_services.breakfastorder')),
            ],
        ),
        migrations.AddField(
            model_name='breakfastorder',
            name='items',
            field=models.ManyToManyField(through='room_services.BreakfastOrderItem', to='room_services.breakfastitem'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_services.order')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_services.roomserviceitem')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='room_services.OrderItem', to='room_services.roomserviceitem'),
        ),
    ]
