# Generated by Django 5.2.1 on 2025-05-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfastitem',
            name='category',
            field=models.CharField(choices=[('Mains', 'Mains'), ('Hot Buffet', 'Hot Buffet'), ('Cold Buffet', 'Cold Buffet'), ('Breads', 'Breads'), ('Condiments', 'Condiments'), ('Drinks', 'Drinks')], default='Mains', max_length=50),
        ),
    ]
