# Generated by Django 5.2.1 on 2025-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_services', '0002_alter_breakfastitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfastitem',
            name='is_on_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomserviceitem',
            name='is_on_stock',
            field=models.BooleanField(default=True),
        ),
    ]
