# Generated by Django 5.2.1 on 2025-05-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_services', '0003_breakfastitem_is_on_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfastorder',
            name='delivery_time',
            field=models.CharField(blank=True, choices=[('7:00-8:00', '7:00 - 8:00'), ('8:00-8:30', '8:00 - 8:30'), ('8:30-9:00', '8:30 - 9:00'), ('9:00-9:30', '9:00 - 9:30'), ('9:30-10:00', '9:30 - 10:00'), ('10:00-10:30', '10:00 - 10:30')], max_length=20, null=True),
        ),
    ]
