# Generated by Django 5.2.1 on 2025-07-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_services', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfastorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
