# Generated by Django 5.2.4 on 2025-11-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_services', '0007_alter_breakfastorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
