# Generated by Django 5.2.4 on 2025-11-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_services', '0008_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfastorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='breakfastorderitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
