# Generated by Django 5.2.1 on 2025-05-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('guest_id_pin', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('room_service_qr_code', models.URLField(blank=True, null=True)),
                ('in_room_breakfast_qr_code', models.URLField(blank=True, null=True)),
                ('guests', models.ManyToManyField(blank=True, related_name='rooms', to='guests.guest')),
            ],
        ),
    ]
