# Generated by Django 5.2.1 on 2025-06-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='dinner_booking_qr_code',
            field=models.URLField(blank=True, null=True),
        ),
    ]
