# Generated by Django 5.2.4 on 2025-08-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_room_dinner_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='chat_pin_qr_code',
            field=models.URLField(blank=True, null=True),
        ),
    ]
