# Generated by Django 5.2.4 on 2025-11-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_room_chat_pin_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest_fcm_token',
            field=models.CharField(blank=True, help_text="Firebase Cloud Messaging token for push notifications to guest's device", max_length=255, null=True),
        ),
    ]
