# Generated by Django 5.2.4 on 2025-11-23 22:49

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_bookingoptions_leisureactivity_offer'),
        ('rooms', '0008_room_guest_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text="Optional identifier (e.g., 'STD', 'DLX')", max_length=50)),
                ('name', models.CharField(help_text="e.g., 'Deluxe Suite', 'Standard Room'", max_length=200)),
                ('short_description', models.TextField(blank=True, help_text='Brief marketing description')),
                ('max_occupancy', models.PositiveSmallIntegerField(default=2, help_text='Maximum number of guests')),
                ('bed_setup', models.CharField(blank=True, help_text="e.g., 'King Bed', '2 Queen Beds'", max_length=100)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, help_text='Room type photo', max_length=255, null=True, verbose_name='room_type_photo')),
                ('starting_price_from', models.DecimalField(decimal_places=2, help_text="Marketing 'from' price per night", max_digits=10)),
                ('currency', models.CharField(default='EUR', help_text='Currency code (e.g., EUR, USD, GBP)', max_length=3)),
                ('booking_code', models.CharField(blank=True, help_text='Code for booking system integration', max_length=50)),
                ('booking_url', models.URLField(blank=True, help_text='Deep link to book this room type')),
                ('availability_message', models.CharField(blank=True, help_text="e.g., 'High demand', 'Last rooms available'", max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this room type is shown publicly')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
