# Generated by Django 5.2.4 on 2025-11-27 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_gallerycontainer_style_variant_and_more'),
        ('rooms', '0009_add_room_type_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Standard Rate', 'Non-Refundable'", max_length=100)),
                ('code', models.CharField(help_text="Short code (e.g., 'STD', 'NRF', 'EB10')", max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_refundable', models.BooleanField(default=True, help_text='Whether bookings under this rate plan can be refunded')),
                ('default_discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Default discount percentage for this rate plan', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate plan is currently available')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Rate Plan',
                'verbose_name_plural': 'Rate Plans',
                'ordering': ['hotel', 'name'],
                'unique_together': {('hotel', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Promo code (case-insensitive)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the promotion', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Internal description or terms')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount (e.g., 20.00 for 20%)', max_digits=5, null=True)),
                ('discount_fixed', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount discount', max_digits=10, null=True)),
                ('valid_from', models.DateField(help_text='Promotion valid from this date')),
                ('valid_until', models.DateField(help_text='Promotion valid until this date')),
                ('min_nights', models.PositiveIntegerField(blank=True, help_text='Minimum nights required for promotion', null=True)),
                ('max_nights', models.PositiveIntegerField(blank=True, help_text='Maximum nights allowed for promotion', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this promotion is currently available')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='hotel.hotel')),
                ('room_types', models.ManyToManyField(blank=True, help_text='Limit to specific room types (empty = all room types)', to='rooms.roomtype')),
                ('rate_plans', models.ManyToManyField(blank=True, help_text='Limit to specific rate plans (empty = all rate plans)', to='rooms.rateplan')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-valid_until', 'code'],
                'indexes': [models.Index(fields=['code', 'is_active'], name='rooms_promo_code_4547c0_idx'), models.Index(fields=['hotel', 'valid_from', 'valid_until'], name='rooms_promo_hotel_i_5484c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Specific date for this rate')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per night for this date', max_digits=10)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rates', to='rooms.roomtype')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rates', to='rooms.rateplan')),
            ],
            options={
                'verbose_name': 'Daily Rate',
                'verbose_name_plural': 'Daily Rates',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['room_type', 'date'], name='rooms_daily_room_ty_df294c_idx'), models.Index(fields=['rate_plan', 'date'], name='rooms_daily_rate_pl_924b59_idx')],
                'unique_together': {('room_type', 'rate_plan', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RoomTypeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for this inventory record')),
                ('total_rooms', models.PositiveIntegerField(blank=True, help_text='If set, overrides physical room count for this date. If null, use physical rooms.', null=True)),
                ('stop_sell', models.BooleanField(default=False, help_text='If true, this room type cannot be booked for this date')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='rooms.roomtype')),
            ],
            options={
                'verbose_name': 'Room Type Inventory',
                'verbose_name_plural': 'Room Type Inventory',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['room_type', 'date'], name='rooms_roomt_room_ty_aefad9_idx')],
                'unique_together': {('room_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RoomTypeRatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Override base price for this room type + rate plan combo', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate plan is active for this room type')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type_links', to='rooms.rateplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plan_links', to='rooms.roomtype')),
            ],
            options={
                'verbose_name': 'Room Type Rate Plan',
                'verbose_name_plural': 'Room Type Rate Plans',
                'unique_together': {('room_type', 'rate_plan')},
            },
        ),
    ]
