# Generated by Django 5.2.4 on 2025-11-27 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_rateplan_promotion_dailyrate_roomtypeinventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this room is available for booking (e.g., false during renovation)'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_out_of_order',
            field=models.BooleanField(default=False, help_text='Temporarily out of service (maintenance, repair, etc.)'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(blank=True, help_text='Links physical room to a room type for PMS inventory tracking', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_rooms', to='rooms.roomtype'),
        ),
    ]
