# Generated by Django 5.2.4 on 2025-11-27 15:16

from django.db import migrations


def assign_room_types_to_killarney_rooms(apps, schema_editor):
    """
    Assign room_type to all 210 physical Room objects for Hotel Killarney (id=2).
    Distribution based on room number ranges across 6 existing room types.
    """
    Room = apps.get_model('rooms', 'Room')
    RoomType = apps.get_model('rooms', 'RoomType')
    Hotel = apps.get_model('hotel', 'Hotel')
    
    # Get Killarney hotel
    try:
        hotel = Hotel.objects.get(id=2)
    except Hotel.DoesNotExist:
        print("Hotel Killarney (id=2) not found. Skipping room type assignment.")
        return
    
    # Get all room types for Killarney, ordered by name for consistency
    room_types = list(RoomType.objects.filter(hotel=hotel).order_by('name'))
    
    if len(room_types) == 0:
        print("No room types found for Killarney. Skipping room type assignment.")
        return
    
    print(f"Found {len(room_types)} room types for Killarney:")
    for rt in room_types:
        print(f"  - {rt.name} (id={rt.id})")
    
    # Room number distribution strategy for 210 rooms across 6 types:
    # We'll use room number ranges to assign types
    # Adjust these ranges based on your actual room numbering
    
    # Get all physical rooms for Killarney
    rooms = Room.objects.filter(hotel=hotel).order_by('room_number')
    total_rooms = rooms.count()
    
    print(f"\nAssigning {total_rooms} physical rooms to room types...")
    
    # Strategy: Distribute rooms evenly across room types
    # If you have 6 types and 210 rooms = 35 rooms per type
    rooms_per_type = total_rooms // len(room_types)
    
    assigned_count = 0
    for idx, room in enumerate(rooms):
        # Calculate which room type index this room belongs to
        type_idx = min(idx // rooms_per_type, len(room_types) - 1)
        room.room_type = room_types[type_idx]
        room.save()
        assigned_count += 1
    
    print(f"✓ Successfully assigned room_type to {assigned_count} rooms")
    print("\nDistribution summary:")
    for rt in room_types:
        count = Room.objects.filter(hotel=hotel, room_type=rt).count()
        print(f"  {rt.name}: {count} rooms")


def reverse_assignment(apps, schema_editor):
    """
    Reverse migration: set all room_type to NULL for Killarney rooms
    """
    Room = apps.get_model('rooms', 'Room')
    Hotel = apps.get_model('hotel', 'Hotel')
    
    try:
        hotel = Hotel.objects.get(id=2)
        Room.objects.filter(hotel=hotel).update(room_type=None)
        print("Reversed room_type assignments for Killarney")
    except Hotel.DoesNotExist:
        print("Hotel Killarney (id=2) not found. Nothing to reverse.")


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_room_is_active_room_is_out_of_order_room_room_type'),
        ('hotel', '0023_gallerycontainer_style_variant_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_room_types_to_killarney_rooms, reverse_assignment),
    ]
