# Generated by Django 5.2.4 on 2025-12-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_assign_room_types_killarney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='guests',
        ),
    ]
