# Generated by Django for Room Turnover Workflow

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_remove_room_guests'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_status',
            field=models.CharField(
                choices=[
                    ('AVAILABLE', 'Available'),
                    ('OCCUPIED', 'Occupied'), 
                    ('CHECKOUT_DIRTY', 'Checkout Dirty'),
                    ('CLEANING_IN_PROGRESS', 'Cleaning in Progress'),
                    ('CLEANED_UNINSPECTED', 'Cleaned Uninspected'),
                    ('MAINTENANCE_REQUIRED', 'Maintenance Required'),
                    ('OUT_OF_ORDER', 'Out of Order'),
                    ('READY_FOR_GUEST', 'Ready for Guest'),
                ],
                default='AVAILABLE',
                help_text='Current turnover workflow status of the room',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='room',
            name='last_cleaned_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When room was last cleaned',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='room',
            name='cleaned_by_staff',
            field=models.ForeignKey(
                blank=True,
                help_text='Staff member who cleaned the room',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cleaned_rooms',
                to='staff.staff',
            ),
        ),
        migrations.AddField(
            model_name='room',
            name='last_inspected_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When room was last inspected',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='room',
            name='inspected_by_staff',
            field=models.ForeignKey(
                blank=True,
                help_text='Staff member who inspected the room',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='inspected_rooms',
                to='staff.staff',
            ),
        ),
        migrations.AddField(
            model_name='room',
            name='turnover_notes',
            field=models.TextField(
                blank=True,
                help_text='Internal turnover workflow notes and history',
            ),
        ),
        migrations.AddField(
            model_name='room',
            name='maintenance_required',
            field=models.BooleanField(
                default=False,
                help_text='Room requires maintenance before next guest',
            ),
        ),
        migrations.AddField(
            model_name='room',
            name='maintenance_priority',
            field=models.CharField(
                blank=True,
                choices=[
                    ('LOW', 'Low Priority'),
                    ('MED', 'Medium Priority'), 
                    ('HIGH', 'High Priority'),
                ],
                help_text='Priority level for maintenance',
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='room',
            name='maintenance_notes',
            field=models.TextField(
                blank=True,
                help_text='Specific maintenance requirements and notes',
            ),
        ),
        # Data migration
        migrations.RunPython(set_initial_room_status, reverse_code=migrations.RunPython.noop),
    ]


def set_initial_room_status(apps, schema_editor):
    """Set initial room_status values based on existing data"""
    Room = apps.get_model('rooms', 'Room')
    for room in Room.objects.all():
        # Note: is_out_of_order remains authoritative flag
        # room_status reflects workflow state regardless
        if room.is_occupied:
            room.room_status = 'OCCUPIED'
        else:
            room.room_status = 'AVAILABLE'
        room.save()