# Generated by Django 5.2.4 on 2025-12-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_room_turnover_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='chat_pin_qr_code',
        ),
        migrations.RemoveField(
            model_name='room',
            name='dinner_booking_qr_code',
        ),
        migrations.RemoveField(
            model_name='room',
            name='guest_id_pin',
        ),
        migrations.RemoveField(
            model_name='room',
            name='in_room_breakfast_qr_code',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_service_qr_code',
        ),
    ]
