# Generated by Django 5.2.4 on 2025-12-20 15:31

from django.db import migrations


def convert_available_to_ready_for_guest(apps, schema_editor):
    """Convert all AVAILABLE room statuses to READY_FOR_GUEST"""
    Room = apps.get_model('rooms', 'Room')
    RoomStatusEvent = apps.get_model('housekeeping', 'RoomStatusEvent')
    
    # Update all rooms with AVAILABLE status
    updated_count = Room.objects.filter(room_status='AVAILABLE').update(
        room_status='READY_FOR_GUEST'
    )
    
    # Update audit trail for these rooms
    RoomStatusEvent.objects.filter(to_status='AVAILABLE').update(
        to_status='READY_FOR_GUEST'
    )
    RoomStatusEvent.objects.filter(from_status='AVAILABLE').update(
        from_status='READY_FOR_GUEST'
    )
    
    print(f"Converted {updated_count} rooms from AVAILABLE to READY_FOR_GUEST")


def reverse_conversion(apps, schema_editor):
    """Reverse: Convert READY_FOR_GUEST back to AVAILABLE (for rollback)"""
    Room = apps.get_model('rooms', 'Room')
    RoomStatusEvent = apps.get_model('housekeeping', 'RoomStatusEvent')
    
    # This is a dangerous reverse operation - only convert rooms that were likely AVAILABLE
    # We'll use a conservative approach and only convert rooms created before this migration
    from django.utils import timezone
    cutoff_date = timezone.now()
    
    updated_count = Room.objects.filter(
        room_status='READY_FOR_GUEST',
        created__lt=cutoff_date
    ).update(room_status='AVAILABLE')
    
    # Reverse audit trail updates
    RoomStatusEvent.objects.filter(to_status='READY_FOR_GUEST').update(
        to_status='AVAILABLE'
    )
    RoomStatusEvent.objects.filter(from_status='READY_FOR_GUEST').update(
        from_status='AVAILABLE'
    )
    
    print(f"Reversed {updated_count} rooms from READY_FOR_GUEST to AVAILABLE")


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_remove_room_chat_pin_qr_code_and_more'),
        ('housekeeping', '0001_initial'),  # Ensure housekeeping models exist
    ]

    operations = [
        migrations.RunPython(
            convert_available_to_ready_for_guest,
            reverse_conversion,
            hints={'target_db': 'default'}
        ),
    ]
