# Generated by Django 5.2.4 on 2025-12-23 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0042_add_cancellation_policies'),
        ('rooms', '0016_convert_available_to_ready_for_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateplan',
            name='cancellation_policy',
            field=models.ForeignKey(blank=True, help_text='Default cancellation policy for bookings using this rate plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_plans', to='hotel.cancellationpolicy'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('OCCUPIED', 'Occupied'), ('CHECKOUT_DIRTY', 'Checkout Dirty'), ('CLEANING_IN_PROGRESS', 'Cleaning in Progress'), ('CLEANED_UNINSPECTED', 'Cleaned Uninspected'), ('MAINTENANCE_REQUIRED', 'Maintenance Required'), ('OUT_OF_ORDER', 'Out of Order'), ('READY_FOR_GUEST', 'Ready for Guest')], default='READY_FOR_GUEST', help_text='Current turnover workflow status of the room', max_length=20),
        ),
    ]
