# Generated by Django 5.2.4 on 2026-04-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0058_add_booking_filter_performance_indexes'),
        ('rooms', '0017_add_cancellation_policies'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomtype',
            unique_together={('hotel', 'name')},
        ),
    ]
