# Generated by Django 5.2.4 on 2026-04-08 11:02

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_alter_roomtype_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(help_text='Room image stored in Cloudinary', max_length=255, verbose_name='room_image')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_cover', models.BooleanField(default=False, help_text='Whether this is the cover/primary image for the room')),
                ('is_dummy', models.BooleanField(default=False, help_text='Placeholder image not uploaded by staff')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
