"""
Django settings for HotelMateBackend project.
Generated by 'django-admin startproject' using Django 5.2.1.
"""

from pathlib import Path
import os
import environ
import dj_database_url
from corsheaders.defaults import default_headers, default_methods
import certifi
import ssl
import sys

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False),
    DISABLE_COLLECTSTATIC=(bool, False),
)
REDIS_URL = env("REDIS_URL")

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


SECRET_KEY = env('SECRET_KEY')


DEBUG = True

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    # Custom apps
    'rooms',
    'guests',
    'staff',
    'room_services.apps.RoomServicesConfig',
    'hotel',
    'bookings',
    'common',
    'notifications',
    'hotel_info.apps.HotelInfoConfig',
    'stock_tracker',
    'ar_navigation',
    'maintenance',
    "channels",
    
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HotelMateBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HotelMateBackend.wsgi.application'

# Database
DATABASES = {
    'default': dj_database_url.parse(env('DATABASE_URL'), conn_max_age=0)
   
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


ASGI_APPLICATION = "HotelMateBackend.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
        "url": env("REDIS_URL"),
        },
    },
}

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files settings (Heroku & WhiteNoise)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Optional media settings if you use Cloudinary
CLOUDINARY_URL = env('CLOUDINARY_URL', default='')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS (adjust if deploying React frontend)
CORS_ALLOWED_ORIGINS = [
    "https://dashing-klepon-d9f0c6.netlify.app",
    "https://hotel-porter-d25ad83b12cf.herokuapp.com",
    "http://localhost:5173",
    "https://hotelsmates.com",
    "https://www.hotelsmates.com",
]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-hotel-id',
    'x-hotel-slug',
    'x-hotel-identifier',
    'authorization',
    'content-type',
]

CORS_ALLOW_CREDENTIALS = True


# Optional
HEROKU_HOST = env('HEROKU_HOST', default='')

# Optional for Heroku: disable collectstatic temporarily
DISABLE_COLLECTSTATIC = env.bool('DISABLE_COLLECTSTATIC', default=False)

# at the bottom of settings.py


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "[%(asctime)s] %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "simple",
        },
    },
    "loggers": {
        # Catch anything in your room_services app
        "room_services": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Channels internals (optional, if you want lower-level debug)
        "channels": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Redis connection errors
        "redis": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
    # Make sure Django’s own logs don’t get lost
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}
