"""
Django settings for HotelMateBackend project.
Generated by 'django-admin startproject' using Django 5.2.1.
"""

from pathlib import Path
import os
import environ
import dj_database_url
from corsheaders.defaults import default_headers, default_methods
import certifi
import ssl
import sys
from urllib.parse import urlparse
# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False),
    DISABLE_COLLECTSTATIC=(bool, False),
)

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
# Read REDIS_URL if present; default to empty so app can run without Redis
REDIS_URL = env("REDIS_URL", default="")

SECRET_KEY = env('SECRET_KEY')


DEBUG = True

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',

    # Third-party
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'dal',
    'dal_select2',
    'cloudinary_storage',
    'cloudinary',
    # Custom apps
    'rooms',
    'guests',
    'staff',
    'room_services.apps.RoomServicesConfig',
    'hotel',
    'bookings',
    'common',
    'notifications',
    'hotel_info.apps.HotelInfoConfig',
    'stock_tracker',
    'maintenance',
    'channels',
    'home',
    'attendance',
    'chat',
    'entertainment',
    'staff_chat',
    'voice_recognition',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Increase field limit for admin forms with many inline items (e.g., stocktakes)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

ROOT_URLCONF = 'HotelMateBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HotelMateBackend.wsgi.application'

# Database
DATABASES = {
    'default': dj_database_url.parse(
        env('DATABASE_URL'),
        conn_max_age=600,  # Keep connections alive for 10 minutes
        conn_health_checks=True  # Check connection health
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


ASGI_APPLICATION = "HotelMateBackend.asgi.application"


# Pusher configuration
PUSHER_APP_ID = env('PUSHER_APP_ID')
PUSHER_KEY = env('PUSHER_KEY')
PUSHER_SECRET = env('PUSHER_SECRET')
PUSHER_CLUSTER = env('PUSHER_CLUSTER')

# Stripe configuration
STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY', default='')
STRIPE_PUBLISHABLE_KEY = env('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_WEBHOOK_SECRET = env('STRIPE_WEBHOOK_SECRET', default='')

# OpenAI configuration for Voice Recognition (Whisper)
OPENAI_API_KEY = env('OPENAI_API_KEY')

# Firebase Cloud Messaging configuration
FIREBASE_CRED_PATH = os.path.join(BASE_DIR, 'firebase-service-account.json')

if os.path.exists(FIREBASE_CRED_PATH):
    # Local development: load from file
    with open(FIREBASE_CRED_PATH) as f:
        FIREBASE_SERVICE_ACCOUNT_JSON = f.read()
else:
    # Heroku: load from environment variable
    FIREBASE_SERVICE_ACCOUNT_JSON = env(
        'FIREBASE_SERVICE_ACCOUNT_JSON', default=''
    )


# Channel layer: prefer a Redis channel layer when REDIS_URL is provided,
# otherwise fall back to the in-memory channel layer (single-process).
if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [{
                    "address": REDIS_URL,
                    "ssl_cert_reqs": ssl.CERT_REQUIRED,
                    "ssl_ca_certs": certifi.where(),
                }],
            },
        },
    }
else:
    # In-memory channel layer is fine for apps that don't need cross-process
    # pub/sub (or when running a single dyno). This lets you remove the
    # Redis add-on safely and keep Channels installed for local dev.
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files settings (Heroku & WhiteNoise)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files settings (user uploads)
# Files stored in Cloudinary cloud storage (not locally)
CLOUDINARY_URL = env('CLOUDINARY_URL', default='')

if CLOUDINARY_URL:
    # Use Cloudinary for media file storage
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    MEDIA_URL = '/media/'  # Cloudinary will serve files
else:
    # Fallback to local storage for development
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cache configuration for payment idempotency and session storage
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'payment_cache_table',
        'TIMEOUT': 1800,  # 30 minutes default timeout
        'OPTIONS': {
            'MAX_ENTRIES': 10000
        }
    }
}

# File upload settings
# Allow files up to 50MB (matches backend validation in chat/views.py)
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB in bytes

# CORS (adjust if deploying React frontend)
CORS_ALLOWED_ORIGINS = [
    "https://dashing-klepon-d9f0c6.netlify.app",
    "https://hotel-porter-d25ad83b12cf.herokuapp.com",
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174", 
    "http://127.0.0.1:3000",
    "https://hotelsmates.com",
    "https://www.hotelsmates.com",
    "https://localhost",  
]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-hotel-id',
    'x-hotel-slug',
    'x-hotel-identifier',
    'authorization',
    'content-type',
]

CORS_ALLOW_CREDENTIALS = True

# For development - allow all localhost origins
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = False  # Keep specific origins for security
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://localhost:\d+$",
        r"^http://127\.0\.0\.1:\d+$",
        r"^https://localhost(:\d+)?$",
    ]

# Optional
HEROKU_HOST = env('HEROKU_HOST', default='')

# Optional for Heroku: disable collectstatic temporarily
DISABLE_COLLECTSTATIC = env.bool('DISABLE_COLLECTSTATIC', default=False)

# at the bottom of settings.py


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "[%(asctime)s] %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "simple",
        },
    },
    "loggers": {
        # Catch anything in your room_services app
        "room_services": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Channels internals (optional, if you want lower-level debug)
        "channels": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Redis connection errors
        "redis": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
    # Make sure Django’s own logs don’t get lost
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}