# Generated by Django 5.2.1 on 2025-05-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('front_office', 'Front Office'), ('front_house', 'Front House'), ('kitchen', 'Kitchen'), ('maintenance', 'Maintenance'), ('leisure', 'Leisure'), ('housekeeping', 'Housekeeping'), ('management', 'Management')], max_length=20)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
