# Generated by Django 5.2.1 on 2025-06-25 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0004_alter_hotel_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('front_office', 'Front Office'), ('front_house', 'Front House'), ('kitchen', 'Kitchen'), ('maintenance', 'Maintenance'), ('leisure', 'Leisure'), ('housekeeping', 'Housekeeping'), ('management', 'Management')], max_length=20)),
                ('role', models.CharField(blank=True, choices=[('porter', 'Porter'), ('receptionist', 'Receptionist'), ('waiter', 'Waiter'), ('chef', 'Chef'), ('supervisor', 'Supervisor'), ('housekeeping_attendant', 'Housekeeping Attendant'), ('manager', 'Manager'), ('technician', 'Technician'), ('security', 'Security'), ('concierge', 'Concierge'), ('leisure_staff', 'Leisure Staff'), ('maintenance_staff', 'Maintenance Staff'), ('other', 'Other')], max_length=50, null=True)),
                ('access_level', models.CharField(choices=[('staff_admin', 'Staff Admin'), ('super_staff_admin', 'Super Staff Admin'), ('regular_staff', 'Regular Staff')], default='regular_staff', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_on_duty', models.BooleanField(default=False)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department', 'last_name'],
            },
        ),
    ]
