# Generated by Django 5.2.1 on 2025-06-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, choices=[('porter', 'Porter'), ('receptionist', 'Receptionist'), ('waiter', 'Waiter'), ('bartender', 'Bartender'), ('chef', 'Chef'), ('supervisor', 'Supervisor'), ('housekeeping_attendant', 'Housekeeping Attendant'), ('manager', 'Manager'), ('technician', 'Technician'), ('security', 'Security'), ('concierge', 'Concierge'), ('leisure_staff', 'Leisure Staff'), ('maintenance_staff', 'Maintenance Staff'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
