# Generated by Django 5.2.1 on 2025-05-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['department', 'last_name']},
        ),
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, choices=[('porter', 'Porter'), ('receptionist', 'Receptionist'), ('waiter', 'Waiter'), ('chef', 'Chef'), ('supervisor', 'Supervisor'), ('housekeeping_attendant', 'Housekeeping Attendant'), ('manager', 'Manager'), ('technician', 'Technician')], max_length=50, null=True),
        ),
    ]
