# Generated by Django 5.2.1 on 2025-05-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_on_duty',
            field=models.BooleanField(default=False),
        ),
    ]
