# Generated by Django 5.2.4 on 2025-07-22 12:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_staff_fcm_token_stafffcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile image'),
        ),
    ]
