# Generated by Django 5.2.4 on 2025-07-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='has_registered_face',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
