# Generated by Django 5.2.1 on 2025-05-28 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_subdomain_alter_hotel_slug'),
        ('staff', '0004_staff_is_on_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
            preserve_default=False,
        ),
    ]
