# Generated by Django 5.2.1 on 2025-06-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staff_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='access_level',
            field=models.CharField(choices=[('staff_admin', 'Staff Admin'), ('super_staff_admin', 'Super Staff Admin'), ('regular_staff', 'Regular Staff')], default='regular_staff', max_length=20),
        ),
    ]
