# Generated by Django 5.2.4 on 2025-07-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staff_has_registered_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('reception', 'Reception'), ('kitchen', 'Kitchen'), ('housekeeping', 'Housekeeping'), ('porters', 'Porters'), ('maintenance', 'Maintenance'), ('leisure', 'Leisure'), ('spa', 'Spa'), ('security', 'Security'), ('management', 'Management'), ('food_and_beverage', 'Food & Beverage'), ('cleaning', 'Cleaning Crew'), ('front_office', 'Front Office')], max_length=20),
        ),
    ]
