# Generated by Django 5.2.1 on 2025-06-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staff_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
