# Generated by Django 5.2.4 on 2025-07-28 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_department_role_alter_staff_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='staff.department'),
        ),
    ]
