# Generated by Django 5.2.4 on 2025-10-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_registrationcode_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffFCMToken',
        ),
    ]
