# Generated by Django 5.2.4 on 2025-11-02 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_logo'),
        ('staff', '0011_alter_staff_first_name_alter_staff_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Home', 'Chat')", max_length=100)),
                ('slug', models.SlugField(help_text="Unique identifier (e.g., 'home', 'chat')", max_length=100)),
                ('path', models.CharField(help_text="Frontend route (e.g., '/', '/chat')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='What this navigation link does', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in navigation menu')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this link is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(help_text='Hotel this navigation item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['hotel', 'display_order', 'name'],
                'unique_together': {('hotel', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='allowed_navigation_items',
            field=models.ManyToManyField(blank=True, help_text='Navigation links this staff member can access', related_name='staff_members', to='staff.navigationitem'),
        ),
    ]
