# Generated by Django 5.2.4 on 2025-11-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_navigationitem_staff_allowed_navigation_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase device token for push notifications', max_length=255, null=True),
        ),
    ]
