# Generated by Django 5.2.4 on 2025-11-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_staff_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcode',
            name='qr_code_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL of the generated QR code', null=True),
        ),
        migrations.AddField(
            model_name='registrationcode',
            name='qr_token',
            field=models.CharField(blank=True, help_text='Unique token embedded in QR code URL', max_length=64, null=True, unique=True),
        ),
    ]
