# Generated by Django 5.2.4 on 2025-11-03 15:44

from django.db import migrations
import secrets


def generate_tokens_for_existing_codes(apps, schema_editor):
    """Generate unique qr_token for all existing RegistrationCode entries"""
    RegistrationCode = apps.get_model('staff', 'RegistrationCode')
    
    for reg_code in RegistrationCode.objects.filter(qr_token__isnull=True):
        # Generate unique token
        token = secrets.token_urlsafe(32)
        # Ensure uniqueness
        while RegistrationCode.objects.filter(qr_token=token).exists():
            token = secrets.token_urlsafe(32)
        
        reg_code.qr_token = token
        reg_code.save()


def reverse_migration(apps, schema_editor):
    """Reverse operation - clear all qr_tokens"""
    RegistrationCode = apps.get_model('staff', 'RegistrationCode')
    RegistrationCode.objects.all().update(qr_token=None)


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_registrationcode_qr_code_url_and_more'),
    ]

    operations = [
        migrations.RunPython(
            generate_tokens_for_existing_codes,
            reverse_migration
        ),
    ]
