# Generated by Django 5.2.4 on 2025-11-30 23:24

from django.db import migrations, models


def sync_duty_status_from_is_on_duty(apps, schema_editor):
    """
    Migrate data from is_on_duty boolean to duty_status choices field.
    """
    Staff = apps.get_model('staff', 'Staff')
    
    for staff in Staff.objects.all():
        if staff.is_on_duty:
            staff.duty_status = 'on_duty'
        else:
            staff.duty_status = 'off_duty'
        staff.save(update_fields=['duty_status'])


def reverse_sync_duty_status(apps, schema_editor):
    """
    Reverse migration: sync back to is_on_duty from duty_status.
    """
    Staff = apps.get_model('staff', 'Staff')
    
    for staff in Staff.objects.all():
        staff.is_on_duty = staff.duty_status in ['on_duty', 'on_break']
        staff.save(update_fields=['is_on_duty'])


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_generate_qr_tokens_for_existing_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='duty_status',
            field=models.CharField(
                choices=[
                    ('off_duty', 'Off Duty'),
                    ('on_duty', 'On Duty'),
                    ('on_break', 'On Break')
                ],
                default='off_duty',
                help_text='Current duty status of the staff member',
                max_length=20
            ),
        ),
        migrations.RunPython(
            sync_duty_status_from_is_on_duty,
            reverse_sync_duty_status
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_on_duty',
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                help_text='Deprecated: Use duty_status instead'
            ),
        ),
    ]
