# Generated by Django 5.2.4 on 2025-11-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_add_duty_status_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_on_duty',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
