# Generated by Django 5.2.4 on 2025-12-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_finalize_duty_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_on_duty',
        ),
    ]
