# Generated by Django 5.2.4 on 2025-12-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_remove_staff_is_on_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_on_duty',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
