# Generated by Django 5.2.4 on 2026-04-02 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0058_add_booking_filter_performance_indexes'),
        ('staff', '0019_staff_is_on_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='role',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('hotel', 'name'), ('hotel', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('hotel', 'name'), ('hotel', 'slug')},
        ),
    ]
