# Generated by Django 5.2.4 on 2026-04-02 11:43

from django.db import migrations


def backfill_department_hotels(apps, schema_editor):
    """
    For each existing Department/Role that has no hotel set,
    find all hotels that use it (through Staff) and duplicate the
    department/role per hotel. Then re-point staff to the hotel-specific copy.
    """
    Department = apps.get_model('staff', 'Department')
    Role = apps.get_model('staff', 'Role')
    Staff = apps.get_model('staff', 'Staff')

    # --- Departments ---
    for dept in list(Department.objects.filter(hotel__isnull=True)):
        hotel_ids = list(
            Staff.objects.filter(department=dept)
            .values_list('hotel_id', flat=True)
            .distinct()
        )
        if not hotel_ids:
            continue

        # First hotel keeps the original row
        first_hotel_id = hotel_ids[0]
        # Check if this hotel already has a dept with same slug
        existing = Department.objects.filter(
            hotel_id=first_hotel_id, slug=dept.slug
        ).exclude(id=dept.id).first()
        if existing:
            # Re-point staff to existing copy
            Staff.objects.filter(
                department=dept, hotel_id=first_hotel_id
            ).update(department=existing)
        else:
            dept.hotel_id = first_hotel_id
            dept.save(update_fields=['hotel_id'])

        # Additional hotels get cloned copies (or re-use existing)
        for hotel_id in hotel_ids[1:]:
            hotel_dept, _ = Department.objects.get_or_create(
                hotel_id=hotel_id,
                slug=dept.slug,
                defaults={
                    'name': dept.name,
                    'description': dept.description,
                },
            )
            Staff.objects.filter(
                department=dept, hotel_id=hotel_id
            ).update(department=hotel_dept)

    # Delete orphan departments (no hotel, no staff pointing to them)
    for dept in Department.objects.filter(hotel__isnull=True):
        if not Staff.objects.filter(department=dept).exists():
            dept.delete()

    # --- Roles ---
    for role in list(Role.objects.filter(hotel__isnull=True)):
        hotel_ids = list(
            Staff.objects.filter(role=role)
            .values_list('hotel_id', flat=True)
            .distinct()
        )
        if not hotel_ids:
            continue

        first_hotel_id = hotel_ids[0]
        # Find matching department in this hotel
        new_dept = None
        if role.department_id:
            new_dept = Department.objects.filter(
                hotel_id=first_hotel_id,
                slug=role.department.slug if role.department else None
            ).first()

        existing_role = Role.objects.filter(
            hotel_id=first_hotel_id, slug=role.slug
        ).exclude(id=role.id).first()
        if existing_role:
            Staff.objects.filter(
                role=role, hotel_id=first_hotel_id
            ).update(role=existing_role)
        else:
            role.hotel_id = first_hotel_id
            if new_dept:
                role.department = new_dept
            role.save(update_fields=['hotel_id', 'department_id'])

        for hotel_id in hotel_ids[1:]:
            # Find matching department in this hotel
            dept_for_hotel = None
            if role.department_id:
                dept_for_hotel = Department.objects.filter(
                    hotel_id=hotel_id,
                    slug=role.department.slug if role.department else None
                ).first()
            hotel_role, _ = Role.objects.get_or_create(
                hotel_id=hotel_id,
                slug=role.slug,
                defaults={
                    'name': role.name,
                    'department': dept_for_hotel,
                    'description': role.description,
                },
            )
            Staff.objects.filter(
                role=role, hotel_id=hotel_id
            ).update(role=hotel_role)

    # Delete orphan roles
    for role in Role.objects.filter(hotel__isnull=True):
        if not Staff.objects.filter(role=role).exists():
            role.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_hotel_scoped_departments_roles'),
    ]

    operations = [
        migrations.RunPython(
            backfill_department_hotels,
            migrations.RunPython.noop,
        ),
    ]
