# Generated by Django 5.2.4 on 2026-04-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_backfill_department_role_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='default_navigation_items',
            field=models.ManyToManyField(blank=True, help_text='Default navigation items for staff with this role', related_name='default_for_roles', to='staff.navigationitem'),
        ),
    ]
