# Generated by Django 5.2.1 on 2025-06-13 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('hotel', '0004_alter_hotel_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themepreference',
            name='user',
        ),
        migrations.AddField(
            model_name='themepreference',
            name='hotel',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='hotel.hotel'),
            preserve_default=False,
        ),
    ]
