# Generated by Django 5.2.4 on 2025-08-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_themepreference_user_themepreference_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='themepreference',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Main background', max_length=7),
        ),
        migrations.AddField(
            model_name='themepreference',
            name='border_color',
            field=models.CharField(default='#dddddd', help_text='Default border color', max_length=7),
        ),
        migrations.AddField(
            model_name='themepreference',
            name='button_color',
            field=models.CharField(default='#2980b9', help_text='Button background', max_length=7),
        ),
        migrations.AddField(
            model_name='themepreference',
            name='button_hover_color',
            field=models.CharField(default='#1f6391', help_text='Hover color for buttons', max_length=7),
        ),
        migrations.AddField(
            model_name='themepreference',
            name='button_text_color',
            field=models.CharField(default='#ffffff', help_text='Button text color', max_length=7),
        ),
        migrations.AddField(
            model_name='themepreference',
            name='link_color',
            field=models.CharField(default='#2980b9', help_text='Default link color', max_length=7),
        ),
        migrations.AddField(
            model_name='themepreference',
            name='link_hover_color',
            field=models.CharField(default='#1f6391', help_text='Hover color for links', max_length=7),
        ),
        migrations.AddField(
            model_name='themepreference',
            name='text_color',
            field=models.CharField(default='#333333', help_text='Default text color', max_length=7),
        ),
        migrations.AlterField(
            model_name='themepreference',
            name='main_color',
            field=models.CharField(default='#3498db', help_text='Primary branding color', max_length=7),
        ),
        migrations.AlterField(
            model_name='themepreference',
            name='secondary_color',
            field=models.CharField(default='#2ecc71', help_text='Secondary accent color', max_length=7),
        ),
    ]
