"""Synonym dictionaries for voice command parsing and matching."""

# Core brand synonyms. Keep keys normalized (lowercase) for quick lookup.
BRAND_SYNONYMS = {
    "budweiser": ["bud", "budwiser", "budweisser", "bude", "budwieser"],
    "bulmers": ["bulmer", "bulmars", "bulmr", "bulmur", "boomer"],
    "smithwicks": ["smithix", "smidix", "smithicks", "smithwix", "smiddicks"],
    "heineken": ["heiny", "heinie", "heinikn", "heine", "heinkin", "hieneken"],
    "peroni": ["perony", "perori", "perni", "perroni", "perrone"],
    "coors": [
        "coors",
        "coors light",
        "coors beer",
        "course",
        "cores",
        "cooors",
        "cors",
        "core",
        "kors",
        "koors",
        "korse",
        "corse",
        "corz",
        "kors light",
    ],
    "guinness": ["guiness", "ginnes", "ginis", "guinnes", "guines"],
    "moretti": ["morety", "moreti", "moretty"],
    "corona": [
        "corona",
        "carona",
        "coronna",
        "corono",
        "korona",
        "korona beer",
    ],
    "carlsberg": ["carlsbrg", "carlsburg"],
    "killarney": [
        "kilani",
        "kellani",
        "killarni",
        "filani",
        "arnie",
        "arny",
        "full circle",
        "fools circle",
        "fuascal",
        "panther",
        "blonde",
    ],
    "cronins": ["cronin", "cronins", "kronin", "kronins"],
    "kopparberg": ["copper", "copperberg", "kopper", "koppar", "kappaberg", "kappenberg"],
    "erdinger": ["airding"],
    "smirnoff ice": ["smirnoff", "smirnof", "smernoff", "smirnov"],
    "wkd": ["wicked", "w k d"],
    "west coast": ["westcoast", "west coast cooler"],
    "orchard thieves": ["orchard", "orchards"],
    "lagunitas": ["lagunita", "lagunitos"],
    "beamish": ["beemish"],
    "murphys": ["murphy", "murphies", "murfy"],
    "sol": ["sol beer", "sol bottle"],
    "absolut": ["absolute", "absoloot"],
    "smirnoff vodka": ["smirnof", "smernoff", "smirnov"],
    "grey goose": ["gray goose", "greygoose", "graygoose"],
    "belvedere": ["belvidere", "belvedeer"],
    "ketel one": ["kettle one", "kettle", "ketel"],
    "titos": ["tito", "teetos", "titos"],
    "dingle vodka": ["dingle"],
    "gordons": ["gordon", "gordans", "gordan", "gordons"],
    "bombay": ["bombay sapphire", "bombay dry", "bumbay"],
    "tanqueray": ["tanquery", "tankery"],
    "hendricks": ["hendrick", "hendrix"],
    "beefeater": ["beefeeter", "beef eater", "beafeater"],
    "dingle gin": ["dingle"],
    "berthas revenge": ["bertha", "berthas", "berthas revenge"],
    "boatyard": ["boat yard", "boatyard sloe"],
    "muckross": ["muckros", "muckross wild"],
    "ring of kerry": ["ring of carry"],
    "silver spear": ["silverspear"],
    "method and madness": ["method madness", "method and madness"],
    "jameson": ["jamesom", "jamison", "jamesons"],
    "bushmills": ["bushmils", "bush mills"],
    "powers": ["power", "powers whiskey"],
    "tullamore": ["tullamore dew"],
    "redbreast": ["red breast", "redbrest"],
    "green spot": ["greenspot"],
    "yellow spot": ["yellowspot"],
    "paddy": ["paddy whiskey", "paddys"],
    "killarney whiskey": ["killarney"],
    "dingle whiskey": ["dingle"],
    "skellig": ["skellig six18"],
    "roe and co": ["roe", "roe and co"],
    "west cork": ["westcork"],
    "jack daniels": ["jack daniel", "jack", "jd"],
    "johnnie walker": ["johnny walker", "jonny walker", "walker"],
    "famous grouse": ["grouse"],
    "glenfiddich": ["glenfidich", "glen fiddich"],
    "glenmorangie": ["glen morangie"],
    "laphroaig": ["lafroyg", "laphroig"],
    "talisker": ["taliska"],
    "black bush": ["blackbush"],
    "crested": ["crested ten", "crested 10"],
    "teachers": ["teacher"],
    "bacardi": ["baccardi", "bakardi"],
    "havana": ["havana club", "havanna"],
    "captain morgan": [
        "captain",
        "captain morgans",
        "cap morgan",
        "captn morgan",
        "kaptain morgan",
    ],
    "malibu": ["maliboo"],
    "kraken": ["krackan", "cracken"],
    "matusalem": ["matuselem"],
    "sea dog": ["seadog"],
    "patron": ["patron silver"],
    "el jimador": ["jimador", "el jimador blanco"],
    "jose cuervo": ["cuervo", "j c", "jc"],
    "olmeca": ["olmeca gold"],
    "corazon": ["corazon anejo"],
    "ghost": ["ghost tequila", "ghost spicy"],
    "tequila rose": ["tequila rosa"],
    "tequila bianca": ["bianca", "tequila blanco"],
    "hennessy": ["hennesy", "henesy"],
    "courvoisier": [
        "cdc",
        "courvoisier",
        "couvoisier",
        "corvoisier",
        "courvosier",
        "cognac cdc",
    ],
    "remy martin": ["remy", "remy vsop"],
    "martell": ["martel", "martell vs"],
    "buffalo trace": ["buffalo", "trace"],
    "canadian club": ["canadian", "cc", "kanadian club"],
    "baileys": ["bailey", "bailies"],
    "kahlua": ["kalua", "kahlu"],
    "tia maria": ["tiamaria"],
    "disaronno": ["disarono", "amaretto"],
    "cointreau": ["cointrau"],
    "grand marnier": ["grandmarnier"],
    "drambuie": ["drambuey"],
    "southern comfort": ["southern"],
    "aperol": ["apparel"],
    "campari": ["campary"],
    "chambord": ["shambor"],
    "luxardo": ["luxardo limoncello"],
    "passoa": ["pasoa", "passion fruit"],
    "midori": ["midori green"],
    "galliano": ["galianos"],
    "sambuca": ["antica sambuca", "sambucca"],
    "pernod": ["perno"],
    "jagermeister": ["jager", "yager"],
    "irish mist": ["irishmist"],
    "benedictine": ["benidictine"],
    "pimms": ["pims", "pimms"],
    "peach schnapps": ["peach schnapps", "peach snaps"],
    "apple sourz": ["apple souz", "apple sours", "sourz"],
    "bols": ["bolls"],
    "volare": ["volari"],
    "triple sec": ["triple", "sec"],
    "limoncello": ["lemoncello", "limoncello"],
    "butterscotch": ["butter scotch", "butterscotch"],
    "passionfruit": ["passion fruit", "passion"],
    "osborne": ["osborne port"],
    "sandeman": ["sandeman port"],
    "tio pepe": ["tio pepe sherry"],
    "harveys": ["harveys bristol cream"],
    "bristol cream": ["bristol", "cream sherry"],
    "port": ["port wine", "porto"],
    "sherry": ["sherry wine"],
    "martini": ["martini vermouth", "vermouth"],
    "chablis": ["shabli", "shably"],
    "merlot": ["merlo", "merloe"],
    "pinot": ["pino", "pinot grigio", "pinot gris"],
    "sauvignon": ["sovignon", "sauvignon blanc", "sauv blanc"],
    "chardonnay": ["chardonny", "chardonay", "shardonnay"],
    "cabernet": ["cab sauv", "cabernet sauvignon"],
    "rioja": ["ryoja", "rio ha"],
    "malbec": ["malbeck"],
    "prosecco": ["proseco"],
    "champagne": ["shampain"],
    "tempranillo": ["temp"],
    "primitivo": ["primativo"],
    "barbera": ["barbera"],
    "albarino": ["albarino", "albarinyo"],
    "verdejo": ["verdejo", "verdayo"],
    "chateau": ["chateau", "chateaux", "shato"],
    "domaine": ["domaine", "domiane"],
    "marquess": ["marques", "marquess plata"],
    "santa ana": ["santa ana", "santana"],
    "jack rabbit": ["jackrabbit", "jack rabbit"],
    "sonnetti": ["sonnetti", "sonetti"],
    "pascaud": ["pacsaud", "pascaud bordeaux"],
    "pouilly": ["pouilly fume", "poilly", "pwilly"],
    "fleurie": ["fleurie", "fleuri"],
    "equino": ["equino malbec"],
    "roquende": ["roquende", "rokende"],
    "fuego": ["fuego blanco", "fuego"],
    "rialto": ["rialto prosecco"],
    "pannier": ["pannier champagne"],
    "collie": ["collie prosecco", "colli"],
    "reina": ["reina wine", "reyna"],
    "pazo": ["pazo albarino", "paso"],
    "tenuta": ["tenuta barbera"],
    "moilard": ["moilard macon", "macon village"],
    "chevaliere": ["chevalier", "chevaliere"],
    "jamelles": ["jamelles", "jamelle"],
    "giola": ["giola colle", "giola"],
    "coca cola": ["coke", "coca", "cola", "cocacola"],
    "seven up": ["7up", "7 up"],
    "sprite": ["sprit"],
    "fanta": ["fanter"],
    "lucozade": ["lucozaid"],
    "schweppes": ["schweps", "schwepps", "elderflower"],
    "fevertree": ["fever tree", "fever-tree"],
    "red bull": ["redbull"],
    "riverrock": ["river rock"],
    "appletiser": ["appletisier", "appletizer"],
    "three cents": ["3 cents"],
    "ginger beer": ["ginger"],
    "lemonade": ["lemonade nashs", "nashs"],
    "miwadi": ["miwadi cordial"],
    "monin": ["monin syrup"],
    "grenadine": ["grenadene"],
    "kulana": ["kulana juice"],
    "splash": ["splash juice"],
    "britvic": ["britvick"],
}

MODIFIER_SYNONYMS = {
    "zero": ["0", "zero alcohol", "non alcoholic", "alcohol free"],
    "diet": ["diet", "lite", "light"],
    "gluten free": ["gf", "gluten free", "celiac"],
    "free": ["free", "0.0", "zero percent"],
    "wild": ["wild berry", "wild fruit"],
    "blonde": ["blond", "blonde ale"],
    "red": ["red ale", "rouge"],
    "white": ["blanc", "blanco", "bianco"],
    "rose": ["rosa", "rosato"],
    "sparkling": ["spark", "fizzy", "bubbles"],
    "still": ["still water", "flat"],
    "mini": ["miniature", "baby", "small"],
    "litre": ["ltr", "liter", "l"],
    "millilitre": ["ml", "milliliter"],
    "centilitre": ["cl"],
    "dozen": ["doz", "12"],
}

PACKAGE_SYNONYMS = {
    "bottle": ["bot", "botle", "botl", "bott", "btl", "bottl"],
    "draught": ["draft", "tap", "on tap", "keg", "kegs"],
    "pint": ["pt", "pnt", "pint bottle"],
    "can": ["cn", "tin"],
    "case": ["case", "box"],
    "split": ["split", "small bottle", "mini"],
}

QUANTITY_WORDS = {
    "one": 1,
    "two": 2,
    "three": 3,
    "four": 4,
    "five": 5,
    "six": 6,
    "seven": 7,
    "eight": 8,
    "nine": 9,
    "ten": 10,
    "half": 0.5,
    "quarter": 0.25,
}

FILLER_WORDS = {"please", "and", "eh", "uh", "um", "a", "the"}

__all__ = [
    "BRAND_SYNONYMS",
    "MODIFIER_SYNONYMS",
    "PACKAGE_SYNONYMS",
    "QUANTITY_WORDS",
    "FILLER_WORDS",
]
