# Generated by Django 5.2.4 on 2025-08-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('staff', '0009_registrationcode_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='roommessage',
            name='sender_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('staff', 'Staff')], default='guest', max_length=10),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_messages', to='staff.staff'),
        ),
    ]
