# Generated by Django 5.2.4 on 2025-08-21 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_roommessage_sender_roommessage_sender_type_and_more'),
        ('rooms', '0006_room_dinner_booking_qr_code'),
        ('staff', '0009_registrationcode_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants_staff', models.ManyToManyField(blank=True, related_name='conversations', to='staff.staff')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='rooms.room')),
            ],
        ),
        migrations.AddField(
            model_name='roommessage',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation'),
            preserve_default=False,
        ),
    ]
