# Generated by Django 5.2.4 on 2025-08-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_roommessage_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='has_unread',
            field=models.BooleanField(default=False),
        ),
    ]
