# Generated by Django 5.2.4 on 2025-11-02 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_has_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='delivered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='guest_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='read_by_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='staff_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('read', 'Read')], default='delivered', max_length=20),
        ),
    ]
