# Generated by Django 5.2.4 on 2025-11-02 18:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_roommessage_delivered_at_roommessage_guest_read_at_and_more'),
        ('rooms', '0007_room_chat_pin_qr_code'),
        ('staff', '0012_navigationitem_staff_allowed_navigation_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='staff_display_name',
            field=models.CharField(blank=True, help_text="Staff name shown to guest (e.g., 'John Smith')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='staff_role_name',
            field=models.CharField(blank=True, help_text="Staff role for guest display (e.g., 'Receptionist')", max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='GuestChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique token stored in guest's browser", unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Session expires after guest checkout or 7 days', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_sessions', to='chat.conversation')),
                ('current_staff_handler', models.ForeignKey(blank=True, help_text='Staff member currently handling this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_guest_sessions', to='staff.staff')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_chat_sessions', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Guest Chat Session',
                'verbose_name_plural': 'Guest Chat Sessions',
                'ordering': ['-last_activity'],
            },
        ),
    ]
