# Generated by Django 5.2.4 on 2025-11-04 13:39

import chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_roommessage_staff_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Message this is replying to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.roommessage'),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Supported: images (jpg, png, gif), documents (pdf, doc, docx, xls, xlsx), text files', max_length=500, upload_to=chat.models.message_attachment_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('pdf', 'PDF'), ('other', 'Other')], default='other', max_length=20)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated thumbnail for images', null=True, upload_to=chat.models.message_attachment_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.roommessage')),
            ],
            options={
                'verbose_name': 'Message Attachment',
                'verbose_name_plural': 'Message Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
