# Generated by Django 5.2.4 on 2025-11-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_roommessage_deleted_at_roommessage_edited_at_and_more'),
    ]

    operations = [
    ]
