# Generated by Django 5.2.4 on 2025-11-04 18:07

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_add_file_attachments_and_message_crud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(help_text='Max 10MB. Supported: images (jpg, png, gif, webp, bmp), PDF, documents (doc, docx, xls, xlsx, txt, csv)', max_length=500, upload_to=chat.models.message_attachment_path, validators=[chat.models.validate_file_size, chat.models.validate_file_extension]),
        ),
    ]
