# Generated by Django 5.2.4 on 2025-11-04 18:55

import chat.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_messageattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[chat.models.validate_file_size, chat.models.validate_file_extension], verbose_name='attachment'),
        ),
    ]
