# Generated by Django 5.2.4 on 2026-01-02 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_messageattachment_file'),
        ('staff', '0019_staff_is_on_duty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommessage',
            name='sender_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('staff', 'Staff'), ('system', 'System')], default='guest', max_length=10),
        ),
        migrations.CreateModel(
            name='GuestConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_participants', to='chat.conversation')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_conversation_participations', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Guest Conversation Participant',
                'verbose_name_plural': 'Guest Conversation Participants',
                'ordering': ['joined_at'],
                'unique_together': {('conversation', 'staff')},
            },
        ),
        migrations.DeleteModel(
            name='GuestChatSession',
        ),
    ]
