# Generated by Django 5.2.4 on 2026-01-05 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_add_guest_conversation_participant'),
        ('hotel', '0051_add_scopes_to_guestbookingtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Booking associated with this message (for guest messages)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='hotel.roombooking'),
        ),
    ]
