# Generated by Django 5.2.4 on 2026-03-27 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_add_booking_to_room_message'),
        ('hotel', '0058_add_booking_filter_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Booking that owns this conversation. Room is contextual metadata.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to='hotel.roombooking'),
        ),
    ]
