# Generated by Django 5.2.4 on 2025-07-12 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0012_booking_room'),
        ('hotel', '0004_alter_hotel_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_url', models.URLField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_anchors', to='hotel.hotel')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_anchors', to='bookings.restaurant')),
            ],
            options={
                'verbose_name_plural': 'AR Anchors',
                'unique_together': {('hotel', 'restaurant')},
            },
        ),
    ]
