# Generated by Django 5.2.1 on 2025-07-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0004_alter_hotel_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor', models.PositiveIntegerField()),
                ('image_url', models.URLField()),
                ('position_hint', models.CharField(help_text='e.g., next to elevator', max_length=100)),
                ('marker_type', models.CharField(choices=[('pattern', 'Pattern'), ('image', 'Image')], default='image', max_length=20)),
                ('instruction', models.TextField(help_text='Instruction shown to user at this point.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('next_anchor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ar_navigation.aranchor')),
            ],
        ),
    ]
