# Generated by Django on YYYY-MM-DD
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('ar_navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aranchor',
            name='restaurant',
            field=models.ForeignKey(
                to='bookings.Restaurant',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ar_anchors',
                null=True,
                blank=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='aranchor',
            unique_together={('hotel','restaurant')},
        ),
    ]
