# Generated by Django 5.2.1 on 2025-07-01 14:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ar_navigation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aranchor',
            name='image_url',
        ),
        migrations.AddField(
            model_name='aranchor',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload the image guests will scan (Cloudinary-hosted).', max_length=255, null=True, verbose_name='marker image'),
        ),
    ]
