# Generated by Django 5.2.4 on 2025-07-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_navigation', '0002_add_restaurant_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='aranchor',
            name='instruction',
            field=models.CharField(default='Hold device about 20 cm above the QR code to open the menu.', help_text='Instruction shown to guests when scanning this QR code.', max_length=100),
        ),
        migrations.AlterField(
            model_name='aranchor',
            name='qr_code_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL of the generated QR code image.', null=True),
        ),
    ]
