# Generated by Django 5.2.4 on 2025-12-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0038_bookingguest_precheckin_payload'),
        ('rooms', '0015_remove_room_chat_pin_qr_code_and_more'),
        ('staff', '0019_staff_is_on_duty'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('TURNOVER', 'Turnover'), ('STAYOVER', 'Stayover'), ('INSPECTION', 'Inspection'), ('DEEP_CLEAN', 'Deep Clean'), ('AMENITY', 'Amenity')], help_text='Type of housekeeping task', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='OPEN', help_text='Current status of the task', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], default='MED', help_text='Priority level of the task', max_length=5)),
                ('note', models.TextField(blank=True, default='', help_text='Additional task notes or instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the task was created')),
                ('started_at', models.DateTimeField(blank=True, help_text='When work on the task began', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task was completed', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to complete the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_housekeeping_tasks', to='staff.staff')),
                ('booking', models.ForeignKey(blank=True, help_text='Associated booking (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.roombooking')),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who created the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_housekeeping_tasks', to='staff.staff')),
                ('hotel', models.ForeignKey(help_text='Hotel where the task is to be performed', on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('room', models.ForeignKey(help_text='Room where the task is to be performed', on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
            options={
                'verbose_name': 'Housekeeping Task',
                'verbose_name_plural': 'Housekeeping Tasks',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['hotel', 'status', 'task_type'], name='housekeepin_hotel_i_bc8203_idx'), models.Index(fields=['assigned_to', 'status'], name='housekeepin_assigne_e4f54b_idx'), models.Index(fields=['room', 'status'], name='housekeepin_room_id_aada97_idx'), models.Index(fields=['hotel', 'priority', '-created_at'], name='housekeepin_hotel_i_ad5749_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(help_text='Previous room status', max_length=20)),
                ('to_status', models.CharField(help_text='New room status', max_length=20)),
                ('source', models.CharField(choices=[('HOUSEKEEPING', 'Housekeeping'), ('FRONT_DESK', 'Front Desk'), ('SYSTEM', 'System'), ('MANAGER_OVERRIDE', 'Manager Override')], default='HOUSEKEEPING', help_text='Source system/department that initiated the change', max_length=20)),
                ('note', models.TextField(blank=True, default='', help_text='Additional notes about the status change')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the status change occurred')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Staff member who initiated the status change', null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
                ('hotel', models.ForeignKey(help_text='Hotel where the room status change occurred', on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('room', models.ForeignKey(help_text='Room that had status changed', on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
            options={
                'verbose_name': 'Room Status Event',
                'verbose_name_plural': 'Room Status Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hotel', 'room', '-created_at'], name='housekeepin_hotel_i_b3ea36_idx'), models.Index(fields=['room', '-created_at'], name='housekeepin_room_id_3be912_idx'), models.Index(fields=['hotel', 'source', '-created_at'], name='housekeepin_hotel_i_6828aa_idx')],
            },
        ),
    ]
