# Generated by Django 5.2.1 on 2025-07-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_guest_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='phone_number',
        ),
    ]
