# Generated by Django 5.2.4 on 2025-12-13 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_remove_guest_email_remove_guest_phone_number'),
        ('hotel', '0027_add_face_attendance_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Links guest to their original booking (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='hotel.roombooking'),
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_type',
            field=models.CharField(choices=[('PRIMARY', 'Primary Guest'), ('COMPANION', 'Companion Guest'), ('WALKIN', 'Walk-in / Manual')], default='WALKIN', help_text='Type of guest: PRIMARY (booking holder), COMPANION (linked to primary), WALKIN (staff-created)', max_length=20),
        ),
        migrations.AddField(
            model_name='guest',
            name='primary_guest',
            field=models.ForeignKey(blank=True, help_text='For COMPANION guests, links to the primary guest who made the booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companions', to='guests.guest'),
        ),
    ]
