# Generated by Django 5.2.4 on 2025-12-13 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_guest_booking_guest_guest_type_guest_primary_guest'),
        ('hotel', '0029_bookingguest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='booking_guest',
            field=models.ForeignKey(blank=True, help_text='Links to the BookingGuest this in-house guest was created from (Phase 3 idempotency)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_house_guest', to='hotel.bookingguest'),
        ),
    ]
