# Generated by Django 5.2.4 on 2025-11-07 16:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0004_alter_hotel_logo'),
        ('staff', '0015_generate_qr_tokens_for_existing_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('code', models.CharField(default='X', max_length=1, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Unknown', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Stock Categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CocktailRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktails', to='hotel.hotel')),
            ],
            options={
                'unique_together': {('name', 'hotel')},
            },
        ),
        migrations.CreateModel(
            name='CocktailConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_made', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='hotel.hotel')),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='stock_tracker.cocktailrecipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='hotel.hotel')),
            ],
            options={
                'unique_together': {('name', 'hotel')},
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Product code (prefix determines category: D/B/S/W/M)', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(help_text="Display format: '50Lt', '70cl', 'Doz'", max_length=50)),
                ('size_value', models.DecimalField(decimal_places=2, help_text='Numeric size: 50, 70, 330', max_digits=10)),
                ('size_unit', models.CharField(help_text='Unit: L, cl, ml, Doz', max_length=10)),
                ('uom', models.DecimalField(decimal_places=2, help_text='Servings per unit (pints/keg, bottles/case, shots/bottle)', max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per FULL unit (keg, case, bottle)', max_digits=10)),
                ('current_full_units', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Full units: kegs, cases, bottles', max_digits=10)),
                ('current_partial_units', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Partial units: pints, loose bottles, % of bottle', max_digits=10)),
                ('menu_price', models.DecimalField(blank=True, decimal_places=2, help_text='Selling price per serving (pint/bottle/shot/glass)', max_digits=10, null=True)),
                ('menu_price_large', models.DecimalField(blank=True, decimal_places=2, help_text='Large serving price (e.g., double shot, large wine)', max_digits=10, null=True)),
                ('bottle_price', models.DecimalField(blank=True, decimal_places=2, help_text='Selling price for whole bottle', max_digits=10, null=True)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, help_text='Promotional/happy hour price', max_digits=10, null=True)),
                ('available_on_menu', models.BooleanField(default=True, help_text='Currently available for sale')),
                ('available_by_bottle', models.BooleanField(default=False, help_text='Can be sold as whole bottle')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Auto-set from SKU prefix', on_delete=django.db.models.deletion.PROTECT, to='stock_tracker.stockcategory')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='hotel.hotel')),
            ],
            options={
                'ordering': ['category__code', 'sku'],
                'unique_together': {('hotel', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='StockPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom Date Range')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('year', models.IntegerField(help_text='2024, 2025, etc.')),
                ('quarter', models.IntegerField(blank=True, help_text='1-4 for quarterly periods', null=True)),
                ('month', models.IntegerField(blank=True, help_text='1-12 for monthly periods', null=True)),
                ('week', models.IntegerField(blank=True, help_text='1-52 for weekly periods', null=True)),
                ('period_name', models.CharField(help_text="e.g., 'October 2024', 'Q4 2024', 'Week 42 2024'", max_length=100)),
                ('is_closed', models.BooleanField(default=False, help_text='Period is finalized and locked')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to='staff.staff')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_periods', to='hotel.hotel')),
            ],
            options={
                'ordering': ['-end_date', '-start_date'],
                'unique_together': {('hotel', 'period_type', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase/Delivery'), ('SALE', 'Sale/Consumption'), ('WASTE', 'Waste/Breakage'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('ADJUSTMENT', 'Stocktake Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity in servings (pints, bottles, shots)', max_digits=15)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Cost per serving at time of movement', max_digits=10, null=True)),
                ('reference', models.CharField(blank=True, help_text='Invoice number, stocktake ID, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='hotel.hotel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock_tracker.stockitem')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='staff.staff')),
                ('period', models.ForeignKey(blank=True, help_text='Period this movement belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='stock_tracker.stockperiod')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stocktakes', to='staff.staff')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktakes', to='hotel.hotel')),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('hotel', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Location name (e.g., 'Spirits Shelf', 'Cellar Rack A-12')", max_length=100)),
                ('active', models.BooleanField(default=True, help_text='Location is active for use')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_locations', to='hotel.hotel')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('hotel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_cocktail', models.FloatField(help_text='Quantity required per single cocktail')),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='stock_tracker.cocktailrecipe')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_tracker.ingredient')),
            ],
            options={
                'unique_together': {('cocktail', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_full_units', models.DecimalField(decimal_places=2, help_text='Full units at period end', max_digits=10)),
                ('closing_partial_units', models.DecimalField(decimal_places=4, help_text='Partial units at period end', max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per unit at period end', max_digits=10)),
                ('cost_per_serving', models.DecimalField(decimal_places=4, help_text='Cost per serving at period end', max_digits=10)),
                ('closing_stock_value', models.DecimalField(decimal_places=2, help_text='Total value at period end', max_digits=12)),
                ('menu_price', models.DecimalField(blank=True, decimal_places=2, help_text='Menu price at period end', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_snapshots', to='hotel.hotel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='stock_tracker.stockitem')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='stock_tracker.stockperiod')),
            ],
            options={
                'ordering': ['-period__end_date', 'item__sku'],
                'unique_together': {('hotel', 'item', 'period')},
            },
        ),
        migrations.CreateModel(
            name='StocktakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_qty', models.DecimalField(decimal_places=4, help_text='Opening quantity in base units', max_digits=15)),
                ('purchases', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('sales', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('waste', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('transfers_in', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('transfers_out', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('adjustments', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Prior adjustments in period', max_digits=15)),
                ('counted_full_units', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Full cases/kegs/bottles counted', max_digits=10)),
                ('counted_partial_units', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Partial units (e.g., 7 bottles from a case)', max_digits=10)),
                ('valuation_cost', models.DecimalField(decimal_places=4, help_text='Cost per base unit for valuation', max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktake_lines', to='stock_tracker.stockitem')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock_tracker.stocktake')),
            ],
            options={
                'ordering': ['item__category__code', 'item__sku'],
                'unique_together': {('stocktake', 'item')},
            },
        ),
    ]
