# Generated by Django 5.2.4 on 2025-11-07 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='category',
            field=models.ForeignKey(help_text='Auto-set from SKU prefix', on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='stock_tracker.stockcategory'),
        ),
    ]
