# Generated by Django 5.2.1 on 2025-06-22 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_logo'),
        ('stock_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Amount moved in or out', max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='hotel.hotel')),
                ('item', models.ForeignKey(help_text='Which defined stock item was moved', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock_tracker.stockitem')),
                ('staff', models.ForeignKey(help_text='Who performed this movement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(help_text='Which storage location this movement applies to', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock_tracker.stock')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-timestamp'],
            },
        ),
    ]
