# Generated by Django 5.2.4 on 2025-11-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0003_add_manual_override_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktakeline',
            name='manual_purchases_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual override: Total purchase value in period (€)', max_digits=15, null=True),
        ),
    ]
