# Generated by Django 5.2.1 on 2025-06-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0003_alter_stockinventory_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='alert_quantity',
            field=models.IntegerField(default=0, help_text='Minimum quantity before alert is triggered'),
        ),
    ]
