# Generated by Django 5.2.4 on 2025-11-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0004_add_manual_override_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktakeline',
            name='manual_sales_profit',
        ),
        migrations.RemoveField(
            model_name='stocktakeline',
            name='sales',
        ),
    ]
