# Generated by Django 5.2.1 on 2025-06-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0004_stockitem_alert_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='active_stock_item',
            field=models.BooleanField(default=False, help_text='Indicates if the item is active in stock inventory'),
        ),
    ]
