# Generated by Django 5.2.1 on 2025-06-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0005_stockitem_active_stock_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('ml', 'Milliliters'), ('l', 'Liters')], help_text='Measurement unit, e.g., ml or l', max_length=2, null=True),
        ),
    ]
