# Generated by Django 5.2.4 on 2025-11-09 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_generate_qr_tokens_for_existing_codes'),
        ('stock_tracker', '0005_remove_sales_from_stocktakeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity sold in servings (pints, bottles, shots, glasses)', max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per serving at time of sale', max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Selling price per serving (for revenue calculation)', max_digits=10, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total cost of goods sold (quantity × unit_cost)', max_digits=15)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Total revenue (quantity × unit_price)', max_digits=15, null=True)),
                ('sale_date', models.DateField(help_text='Date of sale')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales', to='staff.staff')),
                ('item', models.ForeignKey(help_text='Item that was sold', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='stock_tracker.stockitem')),
                ('stocktake', models.ForeignKey(help_text='Stocktake period this sale belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='stock_tracker.stocktake')),
            ],
            options={
                'ordering': ['-sale_date', '-created_at'],
                'indexes': [models.Index(fields=['stocktake', 'item'], name='stock_track_stockta_2ec417_idx'), models.Index(fields=['sale_date'], name='stock_track_sale_da_ef295d_idx')],
            },
        ),
    ]
