# Generated by Django 5.2.1 on 2025-06-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0006_stockitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='volume_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume per bottle/item (e.g., 330 for 330 ml)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('ml', 'Milliliters'), ('l', 'Liters')], help_text='Unit for volume per bottle/item', max_length=10, null=True),
        ),
    ]
