# Generated by Django 5.2.4 on 2025-11-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0006_add_sale_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockperiod',
            name='manual_sales_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual total sales amount for the period (if itemized sales are missing)', max_digits=12, null=True),
        ),
    ]
