# Generated by Django 5.2.4 on 2025-11-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0007_stockperiod_manual_sales_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktakeline',
            name='manual_sales_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual override: Total sales revenue in period (€)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stocktakeline',
            name='manual_waste_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual override: Total waste value in period (€)', max_digits=15, null=True),
        ),
    ]
