# Generated by Django 5.2.1 on 2025-07-05 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0007_stockitem_volume_per_unit_alter_stockitem_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Stock Item Type',
                'verbose_name_plural': 'Stock Item Types',
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_tracker.stockitemtype'),
        ),
    ]
