# Generated by Django 5.2.4 on 2025-11-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0008_stocktakeline_manual_sales_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockperiod',
            name='manual_purchases_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manually entered purchase costs for the period (COGS)', max_digits=12, null=True),
        ),
    ]
