# Generated by Django 5.2.4 on 2025-11-09 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_logo'),
        ('staff', '0015_generate_qr_tokens_for_existing_codes'),
        ('stock_tracker', '0009_stockperiod_manual_purchases_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodReopenPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Permission can be revoked by setting to False')),
                ('notes', models.TextField(blank=True)),
                ('granted_by', models.ForeignKey(blank=True, help_text='Superuser who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_reopen_permissions', to='staff.staff')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_reopen_permissions', to='hotel.hotel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_reopen_permissions', to='staff.staff')),
            ],
            options={
                'ordering': ['-granted_at'],
                'unique_together': {('hotel', 'staff')},
            },
        ),
    ]
