# Generated by Django 5.2.4 on 2025-08-31 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_logo'),
        ('stock_tracker', '0009_cocktailrecipe_ingredient_cocktailconsumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktailconsumption',
            name='hotel',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='hotel.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cocktailrecipe',
            name='hotel',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='cocktails', to='hotel.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='hotel',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='hotel.hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cocktailrecipe',
            unique_together={('name', 'hotel')},
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'hotel')},
        ),
    ]
