# Generated by Django 5.2.4 on 2025-11-09 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_generate_qr_tokens_for_existing_codes'),
        ('stock_tracker', '0010_periodreopenpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockperiod',
            name='reopened_at',
            field=models.DateTimeField(blank=True, help_text='Last time this period was reopened', null=True),
        ),
        migrations.AddField(
            model_name='stockperiod',
            name='reopened_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who last reopened this period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_periods', to='staff.staff'),
        ),
    ]
