# Generated by Django 5.2.4 on 2025-09-04 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0010_cocktailconsumption_hotel_cocktailrecipe_hotel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='stock',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='stock_in_bar',
            field=models.IntegerField(default=0, help_text='Already taken out of storage but unsold'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='direction',
            field=models.CharField(choices=[('in', 'Stock In (Purchase/Delivery)'), ('move_to_bar', 'Moved to Bar'), ('sale', 'Sale'), ('waste', 'Waste/Breakage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock_tracker.stockitem'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
