# Generated by Django 5.2.4 on 2025-11-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0011_stockperiod_reopened_at_stockperiod_reopened_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodreopenpermission',
            name='can_grant_to_others',
            field=models.BooleanField(default=False, help_text='If True, this staff can grant permissions to other staff (like a manager). Only superusers can set this.'),
        ),
    ]
