# Generated by Django 5.2.4 on 2025-09-06 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_logo'),
        ('stock_tracker', '0011_alter_stockmovement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('opening_storage', models.IntegerField(default=0)),
                ('opening_bar', models.IntegerField(default=0)),
                ('added', models.IntegerField(default=0)),
                ('moved_to_bar', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('waste', models.IntegerField(default=0)),
                ('closing_storage', models.IntegerField(default=0)),
                ('closing_bar', models.IntegerField(default=0)),
                ('total_closing_stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_tracker.stockitem')),
            ],
            options={
                'unique_together': {('hotel', 'item', 'start_date', 'end_date')},
            },
        ),
    ]
