# Generated by Django 5.2.4 on 2025-09-10 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_logo'),
        ('stock_tracker', '0012_stockperiod'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockperiod',
            unique_together={('hotel', 'start_date', 'end_date')},
        ),
        migrations.RemoveField(
            model_name='stockperiod',
            name='added',
        ),
        migrations.RemoveField(
            model_name='stockperiod',
            name='closing_bar',
        ),
        migrations.RemoveField(
            model_name='stockperiod',
            name='closing_storage',
        ),
        migrations.RemoveField(
            model_name='stockperiod',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stockperiod',
            name='moved_to_bar',
        ),
        migrations.RemoveField(
            model_name='stockperiod',
            name='opening_bar',
        ),
        migrations.RemoveField(
            model_name='stockperiod',
            name='opening_storage',
        ),
        migrations.RemoveField(
            model_name='stockperiod',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='stockperiod',
            name='total_closing_stock',
        ),
        migrations.RemoveField(
            model_name='stockperiod',
            name='waste',
        ),
        migrations.CreateModel(
            name='StockPeriodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_storage', models.IntegerField(default=0)),
                ('opening_bar', models.IntegerField(default=0)),
                ('added', models.IntegerField(default=0)),
                ('moved_to_bar', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('waste', models.IntegerField(default=0)),
                ('closing_storage', models.IntegerField(default=0)),
                ('closing_bar', models.IntegerField(default=0)),
                ('total_closing_stock', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_tracker.stockitem')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock_tracker.stockperiod')),
            ],
            options={
                'unique_together': {('period', 'item')},
            },
        ),
    ]
