# Generated by Django 5.2.4 on 2025-11-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0012_add_can_grant_to_others_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='par_level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum servings to keep in stock (reorder point)', max_digits=10, null=True),
        ),
    ]
