# Generated by Django 5.2.4 on 2025-11-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0013_add_par_level_to_stock_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktailrecipe',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price per cocktail', max_digits=10, null=True),
        ),
    ]
