# Generated by Django 5.2.4 on 2025-09-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0013_alter_stockperiod_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockperiod',
            name='period_type',
            field=models.CharField(choices=[('week', 'Weekly'), ('month', 'Monthly'), ('half_year', 'Half-Yearly'), ('year', 'Yearly')], default='week', max_length=20),
            preserve_default=False,
        ),
    ]
