# Generated by Django 5.2.4 on 2025-11-06 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0014_stockperiod_period_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinventory',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='stockcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockcategory',
            name='hotel',
        ),
        migrations.AlterUniqueTogether(
            name='stockinventory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockinventory',
            name='item',
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='type',
        ),
        migrations.RemoveField(
            model_name='stockperioditem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='staff',
        ),
        migrations.AlterUniqueTogether(
            name='stockperiod',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockperiod',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='stockperioditem',
            name='period',
        ),
        migrations.AlterUniqueTogether(
            name='stockperioditem',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockCategory',
        ),
        migrations.DeleteModel(
            name='StockInventory',
        ),
        migrations.DeleteModel(
            name='StockItemType',
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
        migrations.DeleteModel(
            name='StockPeriod',
        ),
        migrations.DeleteModel(
            name='StockPeriodItem',
        ),
    ]
