# Generated by Django 5.2.4 on 2025-11-10 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0014_cocktailrecipe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktailconsumption',
            name='stocktake',
            field=models.ForeignKey(blank=True, help_text='Stock period this consumption belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cocktail_consumptions', to='stock_tracker.stockperiod'),
        ),
        migrations.AddField(
            model_name='cocktailconsumption',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total ingredient cost for all cocktails made', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='cocktailconsumption',
            name='total_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total revenue (quantity_made × unit_price)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='cocktailconsumption',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per cocktail at time of consumption', max_digits=10, null=True),
        ),
    ]
