# Generated by Django 5.2.4 on 2025-11-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0015_cocktailconsumption_stocktake_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktailconsumption',
            name='stocktake',
        ),
    ]
