# Generated by Django 5.2.4 on 2025-11-06 02:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_logo'),
        ('stock_tracker', '0016_drop_stock_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_categories', to='hotel.hotel')),
            ],
            options={
                'verbose_name_plural': 'Stock Categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('hotel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('size', models.CharField(help_text='e.g., 70cl, 30Lt, Doz', max_length=50)),
                ('uom', models.DecimalField(decimal_places=2, help_text='Units of measure for conversion (e.g., 12 bottles/case)', max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per full unit (case/keg/bottle)', max_digits=10)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('base_unit', models.CharField(default='ml', help_text='Base unit for calculations (ml, g, pieces)', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='stock_tracker.stockcategory')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='hotel.hotel')),
            ],
            options={
                'ordering': ['category__sort_order', 'code'],
                'unique_together': {('hotel', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase/Delivery'), ('SALE', 'Sale/Consumption'), ('WASTE', 'Waste/Breakage'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('ADJUSTMENT', 'Stocktake Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity in base units', max_digits=15)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Cost per base unit at time of movement', max_digits=10, null=True)),
                ('reference', models.CharField(blank=True, help_text='Invoice number, stocktake ID, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='hotel.hotel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock_tracker.stockitem')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stocktakes', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktakes', to='hotel.hotel')),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('hotel', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='StocktakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_qty', models.DecimalField(decimal_places=4, help_text='Opening quantity in base units', max_digits=15)),
                ('purchases', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('sales', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('waste', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('transfers_in', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('transfers_out', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('adjustments', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Prior adjustments in period', max_digits=15)),
                ('counted_full_units', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Full cases/kegs/bottles counted', max_digits=10)),
                ('counted_partial_units', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Partial units (e.g., 7 bottles from a case)', max_digits=10)),
                ('valuation_cost', models.DecimalField(decimal_places=4, help_text='Cost per base unit for valuation', max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktake_lines', to='stock_tracker.stockitem')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock_tracker.stocktake')),
            ],
            options={
                'ordering': ['item__category__sort_order', 'item__code'],
                'unique_together': {('stocktake', 'item')},
            },
        ),
    ]
