# Generated by Django 5.2.4 on 2025-11-10 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0016_remove_cocktailconsumption_stocktake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='stocktake',
            field=models.ForeignKey(blank=True, help_text='Optional: Stocktake period this sale belongs to. If None, sale is standalone.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='stock_tracker.stocktake'),
        ),
    ]
