# Generated by Django 5.2.4 on 2025-11-06 09:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0017_stockcategory_stockitem_stockmovement_stocktake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='abv_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alcohol by volume percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='active',
            field=models.BooleanField(default=True, help_text='Item is active for ordering'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='case_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total case cost', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='cost_per_base',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Auto-calculated: cost per ml/g/piece', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='country',
            field=models.CharField(blank=True, help_text='Country of origin', max_length=120),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='hide_on_menu',
            field=models.BooleanField(default=False, help_text='Hide from customer menu'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='name',
            field=models.CharField(default='description', help_text='Product name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockitem',
            name='par_level',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Minimum stock level', max_digits=15),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='producer',
            field=models.CharField(blank=True, help_text='Producer/manufacturer', max_length=120),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='product_type',
            field=models.CharField(blank=True, help_text='Wine, Beer, Spirit, Soft Drink, Food, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='region',
            field=models.CharField(blank=True, help_text='Production region', max_length=120),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='size_unit',
            field=models.CharField(blank=True, help_text='cl, ml, L, g, kg', max_length=10),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='size_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric size (e.g., 70)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='subregion',
            field=models.CharField(blank=True, help_text='Sub-region/appellation', max_length=120),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='subtype',
            field=models.CharField(blank=True, help_text='Fortified, Red, IPA, Sparkling, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='tag',
            field=models.CharField(blank=True, help_text='Additional tags for filtering', max_length=100),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='vendor',
            field=models.CharField(blank=True, help_text='Supplier name', max_length=120),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='vineyard',
            field=models.CharField(blank=True, help_text='Vineyard/estate', max_length=120),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='vintage',
            field=models.CharField(blank=True, help_text='Year/vintage', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='code',
            field=models.CharField(help_text='SKU/Product code', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='current_qty',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Current stock in base units', max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed product description'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price per unit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='uom',
            field=models.DecimalField(decimal_places=2, help_text='Units per case (e.g., 12 bottles/case)', max_digits=10),
        ),
    ]
