# Generated by Django 5.2.4 on 2025-11-11 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_generate_qr_tokens_for_existing_codes'),
        ('stock_tracker', '0017_alter_sale_stocktake'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='linked_stock_item',
            field=models.ForeignKey(blank=True, help_text='Optional: Link this ingredient to a stock item for tracking cocktail consumption in inventory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_ingredients', to='stock_tracker.stockitem'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase/Delivery'), ('SALE', 'Sale/Consumption'), ('WASTE', 'Waste/Breakage'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('ADJUSTMENT', 'Stocktake Adjustment'), ('COCKTAIL_CONSUMPTION', 'Cocktail Ingredient Usage (Merged)')], max_length=20),
        ),
        migrations.CreateModel(
            name='CocktailIngredientConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=4, help_text='Total quantity of this ingredient used in the batch', max_digits=15)),
                ('unit', models.CharField(help_text='Unit of measurement (ml, cl, oz, etc.)', max_length=20)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Cost per unit at time of consumption', max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total cost (quantity_used × unit_cost)', max_digits=15, null=True)),
                ('is_merged_to_stocktake', models.BooleanField(default=False, help_text='Has this consumption been manually merged into a stocktake?')),
                ('merged_at', models.DateTimeField(blank=True, help_text='When this was merged into stocktake', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this ingredient consumption was recorded')),
                ('cocktail_consumption', models.ForeignKey(help_text='The cocktail batch this ingredient was used in', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_consumptions', to='stock_tracker.cocktailconsumption')),
                ('ingredient', models.ForeignKey(help_text='The ingredient that was consumed', on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='stock_tracker.ingredient')),
                ('merged_by', models.ForeignKey(blank=True, help_text='Staff member who merged this into stocktake', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_cocktail_consumptions', to='staff.staff')),
                ('merged_to_stocktake', models.ForeignKey(blank=True, help_text='Which stocktake this was merged into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_cocktail_consumptions', to='stock_tracker.stocktake')),
                ('stock_item', models.ForeignKey(blank=True, help_text='Optional link to inventory stock item (if ingredient is in stocktake)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cocktail_consumptions', to='stock_tracker.stockitem')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['stock_item', 'is_merged_to_stocktake'], name='stock_track_stock_i_9421a4_idx'), models.Index(fields=['timestamp'], name='stock_track_timesta_fe6330_idx'), models.Index(fields=['is_merged_to_stocktake'], name='stock_track_is_merg_3219da_idx')],
            },
        ),
    ]
