# Generated by Django 5.2.4 on 2025-11-06 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_logo'),
        ('stock_tracker', '0018_stockitem_abv_percent_stockitem_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='case_upc',
            field=models.CharField(blank=True, help_text='Case barcode/UPC', max_length=64),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='menu_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Menu price per serving', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='serving_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard serving/pour size (e.g., 25, 150)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='serving_unit',
            field=models.CharField(blank=True, default='ml', help_text='Serving unit (ml, oz, cl)', max_length=10),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='unit_upc',
            field=models.CharField(blank=True, help_text='Unit barcode/UPC', max_length=64),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Location name (e.g., 'Spirits Shelf', 'Cellar Rack A-12')", max_length=100)),
                ('active', models.BooleanField(default=True, help_text='Location is active for use')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='hotel.hotel')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('hotel', 'name')},
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='bin',
            field=models.ForeignKey(blank=True, help_text='Default storage location/bin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='stock_tracker.location'),
        ),
    ]
