# Generated by Django 5.2.4 on 2025-11-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_logo'),
        ('stock_tracker', '0019_stockitem_case_upc_stockitem_menu_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['category__sort_order', 'sku']},
        ),
        migrations.AlterModelOptions(
            name='stocktakeline',
            options={'ordering': ['item__category__sort_order', 'item__sku']},
        ),
        migrations.RenameField(
            model_name='stockitem',
            old_name='code',
            new_name='sku',
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('hotel', 'sku')},
        ),
    ]
