# Generated by Django 5.2.4 on 2025-11-06 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_generate_qr_tokens_for_existing_codes'),
        ('stock_tracker', '0020_alter_stockitem_options_alter_stocktakeline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stocktakes', to='staff.staff'),
        ),
    ]
