# Generated by Django 5.2.4 on 2025-11-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0021_fix_minerals_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('SOFT_DRINKS', 'Soft Drinks (Bottled)'), ('SYRUPS', 'Syrups & Flavourings'), ('JUICES', 'Juices & Lemonades'), ('CORDIALS', 'Cordials'), ('BIB', 'Bag-in-Box (18L)'), ('BULK_JUICES', 'Bulk Juices (Individual Bottles)')], help_text='Sub-category for Minerals (M) items only', max_length=20, null=True),
        ),
    ]
