# Generated by Django 5.2.1 on 2025-05-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='subdomain',
            field=models.SlugField(blank=True, help_text="Used as the subdomain, e.g., 'hilton' → hilton.example.com", null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(help_text='Used in URLs, e.g., hotel-name', unique=True),
        ),
    ]
