# Generated by Django 5.2.1 on 2025-06-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_subdomain_alter_hotel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload a logo for this hotel (recommended PNG).', null=True, upload_to='hotel_logos/'),
        ),
    ]
