# Generated by Django 5.2.1 on 2025-06-13 08:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a logo for this hotel (PNG recommended).', max_length=255, null=True, verbose_name='logo'),
        ),
    ]
