# Generated by Django 5.2.4 on 2025-11-23 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If false, the hotel is hidden from public/guest listings.'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short marketing blurb for the hotel.'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls ordering on HotelsMate landing page.'),
        ),
        migrations.CreateModel(
            name='HotelAccessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_portal_enabled', models.BooleanField(default=True, help_text='If false, guest portal features are disabled for this hotel.')),
                ('staff_portal_enabled', models.BooleanField(default=True, help_text='If false, staff portal login/features are disabled for this hotel.')),
                ('requires_room_pin', models.BooleanField(default=True, help_text='If disabled, the magic link alone grants guest access.')),
                ('room_pin_length', models.PositiveSmallIntegerField(default=4, help_text='Number of digits in room PIN (e.g. 4 or 6).')),
                ('rotate_pin_on_checkout', models.BooleanField(default=True, help_text='Regenerate a fresh PIN when the room is checked out.')),
                ('allow_multiple_guest_sessions', models.BooleanField(default=True, help_text='Allow multiple devices/people in the same room to share access.')),
                ('max_active_guest_devices_per_room', models.PositiveSmallIntegerField(default=5, help_text='Hard limit of concurrent guest sessions per room.')),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_config', to='hotel.hotel')),
            ],
        ),
    ]
