# Generated by Django 5.2.4 on 2025-11-23 17:44

from django.db import migrations


def create_access_configs_for_existing_hotels(apps, schema_editor):
    """
    Create HotelAccessConfig for all existing hotels that don't have one.
    """
    Hotel = apps.get_model('hotel', 'Hotel')
    HotelAccessConfig = apps.get_model('hotel', 'HotelAccessConfig')
    
    for hotel in Hotel.objects.all():
        HotelAccessConfig.objects.get_or_create(
            hotel=hotel,
            defaults={
                'guest_portal_enabled': True,
                'staff_portal_enabled': True,
                'requires_room_pin': True,
                'room_pin_length': 4,
                'rotate_pin_on_checkout': True,
                'allow_multiple_guest_sessions': True,
                'max_active_guest_devices_per_room': 5,
            }
        )


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - remove all HotelAccessConfig records.
    """
    HotelAccessConfig = apps.get_model('hotel', 'HotelAccessConfig')
    HotelAccessConfig.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_city_hotel_country_hotel_is_active_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_access_configs_for_existing_hotels,
            reverse_migration
        ),
    ]
