# Generated by Django 5.2.4 on 2025-11-23 22:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_create_access_config_for_existing_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='Street address line 1', max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Street address line 2 (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='booking_url',
            field=models.URLField(blank=True, help_text='Primary booking URL (external or internal)'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, help_text='Main contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Hero/banner image for public hotel page', max_length=255, null=True, verbose_name='hero_image'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for map display', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='long_description',
            field=models.TextField(blank=True, help_text='Detailed description for the hotel public page'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for map display', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, help_text='Main contact phone number', max_length=30),
        ),
        migrations.AddField(
            model_name='hotel',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tagline',
            field=models.CharField(blank=True, help_text="Catchy tagline for hotel marketing (e.g., 'Luxury in the heart of the city')", max_length=200),
        ),
        migrations.AddField(
            model_name='hotel',
            name='website_url',
            field=models.URLField(blank=True, help_text="Hotel's official website URL"),
        ),
    ]
