# Generated by Django 5.2.4 on 2025-11-23 22:48

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_add_public_page_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_cta_label', models.CharField(default='Book a Room', help_text='Label for primary booking button', max_length=100)),
                ('primary_cta_url', models.URLField(blank=True, help_text='URL for primary booking action')),
                ('secondary_cta_label', models.CharField(blank=True, help_text="Label for secondary action (e.g., 'Call to Book')", max_length=100)),
                ('secondary_cta_phone', models.CharField(blank=True, help_text='Phone number for secondary CTA', max_length=30)),
                ('terms_url', models.URLField(blank=True, help_text='URL to terms and conditions')),
                ('policies_url', models.URLField(blank=True, help_text='URL to booking policies')),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_options', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Booking Options',
                'verbose_name_plural': 'Booking Options',
            },
        ),
        migrations.CreateModel(
            name='LeisureActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Indoor Pool', 'Spa & Wellness'", max_length=200)),
                ('category', models.CharField(choices=[('Wellness', 'Wellness'), ('Family', 'Family'), ('Dining', 'Dining'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Business', 'Business'), ('Other', 'Other')], help_text='Activity category', max_length=50)),
                ('short_description', models.TextField(help_text='Brief description of the activity/facility')),
                ('details_html', models.TextField(blank=True, help_text='Detailed HTML description')),
                ('icon', models.CharField(blank=True, help_text='Icon name or CSS class', max_length=50)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Image for the activity/facility', max_length=255, null=True, verbose_name='activity_image')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this activity is currently available')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leisure_activities', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Leisure Activity',
                'verbose_name_plural': 'Leisure Activities',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Weekend Getaway Package'", max_length=200)),
                ('short_description', models.TextField(help_text='Brief description of the offer')),
                ('details_text', models.TextField(blank=True, help_text='Plain text details')),
                ('details_html', models.TextField(blank=True, help_text='Rich HTML for detailed description')),
                ('valid_from', models.DateField(blank=True, help_text='Offer valid from this date', null=True)),
                ('valid_to', models.DateField(blank=True, help_text='Offer valid until this date', null=True)),
                ('tag', models.CharField(blank=True, help_text="e.g., 'Family Deal', 'Weekend Offer'", max_length=50)),
                ('book_now_url', models.URLField(blank=True, help_text='Direct link to book this offer')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, help_text='Promotional image for the offer', max_length=255, null=True, verbose_name='offer_photo')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this offer is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
