# Generated by Django 5.2.4 on 2025-11-24 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_bookingoptions_leisureactivity_offer'),
        ('rooms', '0009_add_room_type_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adults', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField(default=0)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_nights', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('promo_code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(help_text='Quote expiration timestamp')),
                ('applied_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.offer')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_quotes', to='hotel.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, help_text='Auto-generated booking ID (e.g., BK-2025-5678)', max_length=50, unique=True)),
                ('confirmation_number', models.CharField(editable=False, help_text='Guest-facing confirmation number', max_length=50, unique=True)),
                ('check_in', models.DateField(help_text='Check-in date')),
                ('check_out', models.DateField(help_text='Check-out date')),
                ('guest_first_name', models.CharField(help_text='Guest first name', max_length=100)),
                ('guest_last_name', models.CharField(help_text='Guest last name', max_length=100)),
                ('guest_email', models.EmailField(help_text='Guest email for confirmation', max_length=254)),
                ('guest_phone', models.CharField(blank=True, help_text='Guest contact phone', max_length=30)),
                ('adults', models.PositiveIntegerField(default=1, help_text='Number of adults')),
                ('children', models.PositiveIntegerField(default=0, help_text='Number of children')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount charged', max_digits=10)),
                ('currency', models.CharField(default='EUR', help_text='Currency code (ISO 4217)', max_length=3)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='PENDING_PAYMENT', max_length=20)),
                ('special_requests', models.TextField(blank=True, help_text='Guest special requests')),
                ('promo_code', models.CharField(blank=True, help_text='Applied promotional code', max_length=50)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment processor reference ID', max_length=200)),
                ('payment_provider', models.CharField(blank=True, help_text='Payment provider (stripe, paypal, etc.)', max_length=50)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp of successful payment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Booking creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal staff notes (not visible to guest)')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_bookings', to='hotel.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.roomtype')),
            ],
            options={
                'verbose_name': 'Room Booking',
                'verbose_name_plural': 'Room Bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hotel', 'check_in', 'check_out'], name='hotel_roomb_hotel_i_077bd5_idx'), models.Index(fields=['booking_id'], name='hotel_roomb_booking_44e4fc_idx'), models.Index(fields=['guest_email'], name='hotel_roomb_guest_e_d67049_idx'), models.Index(fields=['status'], name='hotel_roomb_status_324e79_idx')],
            },
        ),
    ]
