# Generated by Django 5.2.4 on 2025-11-24 12:31

from django.db import migrations
from datetime import date, timedelta


def populate_public_hotel_data(apps, schema_editor):
    """Populate BookingOptions, RoomTypes, Offers, and LeisureActivities."""
    Hotel = apps.get_model('hotel', 'Hotel')
    BookingOptions = apps.get_model('hotel_info', 'BookingOptions')
    RoomType = apps.get_model('hotel_info', 'RoomType')
    Offer = apps.get_model('hotel_info', 'Offer')
    LeisureActivity = apps.get_model('hotel_info', 'LeisureActivity')
    
    # Get all hotels
    hotels = Hotel.objects.all()
    
    for hotel in hotels:
        # Create BookingOptions
        booking_options, _ = BookingOptions.objects.get_or_create(
            hotel=hotel,
            defaults={
                'primary_cta_label': 'Book Your Stay',
                'primary_cta_url': f'https://booking.{hotel.slug}.com',
                'secondary_cta_label': 'Call to Reserve',
                'secondary_cta_phone': hotel.phone if hotel.phone else '+353 1 234 5678',
                'terms_url': f'https://{hotel.slug}.com/terms',
                'policies_url': f'https://{hotel.slug}.com/policies',
            }
        )
        
        # Create Room Types
        room_types_data = [
            {
                'code': 'STD',
                'name': 'Standard Room',
                'short_description': 'Comfortable room with modern amenities',
                'max_occupancy': 2,
                'bed_setup': 'Queen Bed',
                'starting_price_from': '89.00',
                'currency': 'EUR',
                'booking_code': 'STD-ROOM',
                'is_active': True,
                'sort_order': 1,
            },
            {
                'code': 'DLX',
                'name': 'Deluxe Suite',
                'short_description': 'Spacious suite with separate living area',
                'max_occupancy': 3,
                'bed_setup': 'King Bed + Sofa Bed',
                'starting_price_from': '159.00',
                'currency': 'EUR',
                'booking_code': 'DLX-SUITE',
                'is_active': True,
                'sort_order': 2,
            },
            {
                'code': 'FAM',
                'name': 'Family Room',
                'short_description': 'Perfect for families with children',
                'max_occupancy': 4,
                'bed_setup': '2 Queen Beds',
                'starting_price_from': '129.00',
                'currency': 'EUR',
                'booking_code': 'FAM-ROOM',
                'is_active': True,
                'sort_order': 3,
            },
        ]
        
        for room_data in room_types_data:
            RoomType.objects.get_or_create(
                hotel=hotel,
                code=room_data['code'],
                defaults=room_data
            )
        
        # Create Offers
        today = date.today()
        offers_data = [
            {
                'title': 'Weekend Getaway Package',
                'short_description': 'Escape for the weekend with special rates',
                'details_html': '<p>Includes breakfast and late checkout</p>',
                'valid_from': today,
                'valid_to': today + timedelta(days=90),
                'tag': 'Weekend Special',
                'is_active': True,
                'sort_order': 1,
            },
            {
                'title': 'Family Summer Deal',
                'short_description': 'Kids stay free with special summer rates',
                'details_html': '<p>Two kids under 12 stay free</p>',
                'valid_from': today,
                'valid_to': today + timedelta(days=120),
                'tag': 'Family Package',
                'is_active': True,
                'sort_order': 2,
            },
            {
                'title': 'Romantic Dinner & Stay',
                'short_description': 'Perfect for couples celebrating',
                'details_html': '<p>Includes 3-course dinner and champagne</p>',
                'valid_from': today,
                'valid_to': today + timedelta(days=60),
                'tag': 'Romance Package',
                'is_active': True,
                'sort_order': 3,
            },
        ]
        
        for offer_data in offers_data:
            Offer.objects.get_or_create(
                hotel=hotel,
                title=offer_data['title'],
                defaults=offer_data
            )
        
        # Create Leisure Activities
        activities_data = [
            {
                'name': 'Indoor Pool',
                'category': 'WELLNESS',
                'short_description': 'Heated indoor swimming pool',
                'details_html': '<p>Open daily 6am-10pm</p>',
                'icon': 'swimming-pool',
                'is_active': True,
                'sort_order': 1,
            },
            {
                'name': 'Kids Club',
                'category': 'FAMILY',
                'short_description': 'Supervised activities for children',
                'details_html': '<p>Ages 4-12, daily 9am-5pm</p>',
                'icon': 'child',
                'is_active': True,
                'sort_order': 2,
            },
            {
                'name': 'Fine Dining Restaurant',
                'category': 'DINING',
                'short_description': 'Award-winning restaurant',
                'details_html': '<p>Dinner 6pm-10pm, reservations recommended</p>',
                'icon': 'restaurant',
                'is_active': True,
                'sort_order': 3,
            },
            {
                'name': 'Fitness Center',
                'category': 'SPORTS',
                'short_description': 'Modern gym with equipment',
                'details_html': '<p>24/7 access for guests</p>',
                'icon': 'dumbbell',
                'is_active': True,
                'sort_order': 4,
            },
            {
                'name': 'Spa & Wellness',
                'category': 'WELLNESS',
                'short_description': 'Luxury spa treatments',
                'details_html': '<p>Massages, facials, and more</p>',
                'icon': 'spa',
                'is_active': True,
                'sort_order': 5,
            },
        ]
        
        for activity_data in activities_data:
            LeisureActivity.objects.get_or_create(
                hotel=hotel,
                name=activity_data['name'],
                defaults=activity_data
            )


def reverse_populate(apps, schema_editor):
    """Remove populated data."""
    BookingOptions = apps.get_model('hotel_info', 'BookingOptions')
    RoomType = apps.get_model('hotel_info', 'RoomType')
    Offer = apps.get_model('hotel_info', 'Offer')
    LeisureActivity = apps.get_model('hotel_info', 'LeisureActivity')
    
    # Delete all created data
    BookingOptions.objects.all().delete()
    RoomType.objects.all().delete()
    Offer.objects.all().delete()
    LeisureActivity.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_pricingquote_roombooking'),
        ('hotel_info', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            populate_public_hotel_data,
            reverse_code=reverse_populate
        ),
    ]
