# Generated by Django 5.2.4 on 2025-11-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_populate_public_hotel_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPublicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(blank=True, default='', help_text='Brief description for the hotel')),
                ('long_description', models.TextField(blank=True, default='', help_text='Detailed description for the public page')),
                ('welcome_message', models.TextField(blank=True, default='', help_text='Welcome message for guests (optional)')),
                ('hero_image', models.URLField(blank=True, default='', help_text='URL for hero/banner image')),
                ('gallery', models.JSONField(blank=True, default=list, help_text='List of image URLs for gallery')),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of amenity strings')),
                ('contact_email', models.EmailField(blank=True, default='', help_text='Public contact email', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', help_text='Public contact phone number', max_length=30)),
                ('contact_address', models.TextField(blank=True, default='', help_text='Full contact address')),
                ('primary_color', models.CharField(blank=True, default='#3B82F6', help_text='Primary brand color (HEX format)', max_length=7)),
                ('secondary_color', models.CharField(blank=True, default='#10B981', help_text='Secondary brand color (HEX format)', max_length=7)),
                ('accent_color', models.CharField(blank=True, default='#F59E0B', help_text='Accent color (HEX format)', max_length=7)),
                ('background_color', models.CharField(blank=True, default='#FFFFFF', help_text='Background color (HEX format)', max_length=7)),
                ('button_color', models.CharField(blank=True, default='#3B82F6', help_text='Button color (HEX format)', max_length=7)),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('custom', 'Custom')], default='light', help_text='Theme mode for the public page', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(help_text='Hotel this settings configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='public_settings', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Public Settings',
                'verbose_name_plural': 'Hotel Public Settings',
            },
        ),
    ]
