# Generated by Django 5.2.4 on 2025-11-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_hotelpublicsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='border_color',
            field=models.CharField(blank=True, default='#E5E7EB', help_text='Border color (HEX format)', max_length=7),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='button_hover_color',
            field=models.CharField(blank=True, default='#0066CC', help_text='Button hover state color (HEX format)', max_length=7),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='button_text_color',
            field=models.CharField(blank=True, default='#FFFFFF', help_text='Button text color (HEX format)', max_length=7),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='link_color',
            field=models.CharField(blank=True, default='#007BFF', help_text='Link color (HEX format)', max_length=7),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='link_hover_color',
            field=models.CharField(blank=True, default='#0056B3', help_text='Link hover color (HEX format)', max_length=7),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='text_color',
            field=models.CharField(blank=True, default='#333333', help_text='Main text color (HEX format)', max_length=7),
        ),
    ]
