# Generated by Django 5.2.4 on 2025-11-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_hotelpublicsettings_border_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='favicon',
            field=models.URLField(blank=True, default='', help_text='Favicon URL (16x16 or 32x32px)'),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='google_maps_link',
            field=models.URLField(blank=True, default='', help_text='Google Maps embed/link URL'),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='logo',
            field=models.URLField(blank=True, default='', help_text='Hotel logo URL'),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='slogan',
            field=models.CharField(blank=True, default='', help_text='Hotel slogan/tagline', max_length=200),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='website',
            field=models.URLField(blank=True, default='', help_text='Hotel website URL'),
        ),
    ]
