# Generated by Django 5.2.4 on 2025-11-24 20:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_hotelpublicsettings_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='landing_page_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image displayed on landing page hotel card', max_length=255, null=True, verbose_name='landing_page_image'),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='address_line_1_override',
            field=models.CharField(blank=True, help_text='Custom address line 1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='address_line_2_override',
            field=models.CharField(blank=True, help_text='Custom address line 2', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='booking_url_override',
            field=models.URLField(blank=True, help_text='Custom booking URL', null=True),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='city_override',
            field=models.CharField(blank=True, help_text='Custom city for public display', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='country_override',
            field=models.CharField(blank=True, help_text='Custom country for public display', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='email_override',
            field=models.EmailField(blank=True, help_text='Custom email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='landing_page_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image for hotel card on landing page (customizable)', max_length=255, null=True, verbose_name='settings_landing_page_image'),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='latitude_override',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Custom latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='longitude_override',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Custom longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='name_override',
            field=models.CharField(blank=True, help_text='Custom hotel name for public display', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='phone_override',
            field=models.CharField(blank=True, help_text='Custom phone number', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='postal_code_override',
            field=models.CharField(blank=True, help_text='Custom postal code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='tagline_override',
            field=models.CharField(blank=True, help_text='Custom tagline for public display', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotelpublicsettings',
            name='website_url_override',
            field=models.URLField(blank=True, help_text='Custom website URL', null=True),
        ),
        migrations.AlterField(
            model_name='hotelpublicsettings',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Hero/banner image for public page (customizable)', max_length=255, null=True, verbose_name='settings_hero_image'),
        ),
    ]
