# Generated by Django 5.2.4 on 2025-11-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_hotel_landing_page_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="List of tags for filtering (e.g., ['Family', 'Spa', 'Business'])"),
        ),
    ]
