# Generated by Django 5.2.4 on 2025-11-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_hotel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_type',
            field=models.CharField(blank=True, choices=[('Resort', 'Resort'), ('SpaHotel', 'Spa Hotel'), ('WellnessHotel', 'Wellness Hotel'), ('FamilyHotel', 'Family Hotel'), ('BusinessHotel', 'Business Hotel'), ('LuxuryHotel', 'Luxury Hotel'), ('BoutiqueHotel', 'Boutique Hotel'), ('BudgetHotel', 'Budget Hotel'), ('Hostel', 'Hostel'), ('Aparthotel', 'Aparthotel'), ('EcoHotel', 'Eco Hotel'), ('ConferenceHotel', 'Conference Hotel'), ('BeachHotel', 'Beach Hotel'), ('MountainHotel', 'Mountain Hotel'), ('CasinoHotel', 'Casino Hotel'), ('GolfHotel', 'Golf Hotel'), ('AirportHotel', 'Airport Hotel'), ('AdventureHotel', 'Adventure Hotel'), ('CityHotel', 'City Hotel'), ('HistoricHotel', 'Historic Hotel')], default='', help_text='Primary hotel type classification', max_length=50),
        ),
    ]
