# Generated by Django 5.2.4 on 2025-11-25 12:24

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_hotel_hotel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='gallery',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs for public hotel gallery'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Gallery name (e.g., 'Luxury Rooms', 'Pool Area')", max_length=100)),
                ('category', models.CharField(choices=[('rooms', 'Rooms'), ('facilities', 'Facilities'), ('dining', 'Dining & Restaurant'), ('spa', 'Spa & Wellness'), ('events', 'Events & Conferences'), ('exterior', 'Exterior & Grounds'), ('activities', 'Activities'), ('other', 'Other')], default='other', help_text='Category for organizing galleries', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description for this gallery')),
                ('is_active', models.BooleanField(default=True, help_text='Show this gallery on public page')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which galleries are displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'ordering': ['display_order', 'name'],
                'unique_together': {('hotel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(help_text='Gallery image stored on Cloudinary', max_length=255, verbose_name='gallery_image')),
                ('caption', models.CharField(blank=True, help_text='Description/caption for this image', max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order within the gallery')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this image (e.g., as gallery thumbnail)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel.gallery')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['display_order', 'uploaded_at'],
            },
        ),
    ]
