# Generated by Django 5.2.4 on 2025-11-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_hotel_gallery_gallery_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='gallery',
        ),
    ]
