# Generated by Django 5.2.4 on 2025-11-26 00:50

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_publicelement_publicelementitem_publicsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional gallery name/title', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='hotel.publicsection')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(help_text='Gallery image stored in Cloudinary', max_length=255, verbose_name='gallery_image')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel.gallerycontainer')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Update your hero title here', max_length=255)),
                ('hero_text', models.TextField(default='Update your hero description text here.')),
                ('hero_image', cloudinary.models.CloudinaryField(blank=True, help_text='Main hero background image', max_length=255, null=True, verbose_name='hero_image')),
                ('hero_logo', cloudinary.models.CloudinaryField(blank=True, help_text='Corner logo image', max_length=255, null=True, verbose_name='hero_logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero_data', to='hotel.publicsection')),
            ],
        ),
        migrations.CreateModel(
            name='ListContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Optional list title (e.g., 'Special Offers', 'Rooms & Suites')", max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='hotel.publicsection')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Optional card image', max_length=255, null=True, verbose_name='card_image')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='hotel.listcontainer')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, help_text='Publication date', null=True)),
                ('summary', models.CharField(blank=True, help_text='Short summary/excerpt', max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='hotel.publicsection')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text Block'), ('image', 'Image Block')], default='text', max_length=20)),
                ('body', models.TextField(blank=True, help_text='Text content (supports rich text/markdown)')),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Image for image blocks', max_length=255, null=True, verbose_name='news_image')),
                ('image_position', models.CharField(blank=True, choices=[('full_width', 'Full Width'), ('left', 'Left (text right)'), ('right', 'Right (text left)'), ('inline_grid', 'Inline Grid')], default='full_width', max_length=20)),
                ('image_caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='hotel.newsitem')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
