# Generated by Django 5.2.4 on 2025-11-26 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_gallerycontainer_galleryimage_herosection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('section', 'Section'), ('card', 'Card'), ('image', 'Image'), ('news_block', 'News Block'), ('footer', 'Footer'), ('page_theme', 'Page Theme')], max_length=20)),
                ('section_type', models.CharField(blank=True, choices=[('hero', 'Hero'), ('gallery', 'Gallery'), ('list', 'List'), ('news', 'News'), ('footer', 'Footer')], help_text="Required when target_type='section'.", max_length=20, null=True)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['target_type', 'section_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='style_preset',
            field=models.ForeignKey(blank=True, help_text='Style preset for this card', limit_choices_to={'target_type': 'card'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.preset'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='block_preset',
            field=models.ForeignKey(blank=True, help_text='Style preset for this content block', limit_choices_to={'target_type': 'news_block'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.preset'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_style_preset',
            field=models.ForeignKey(blank=True, help_text='Style preset for this image', limit_choices_to={'target_type': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.preset'),
        ),
        migrations.AddField(
            model_name='publicsection',
            name='layout_preset',
            field=models.ForeignKey(blank=True, help_text='Layout preset for this section', limit_choices_to={'target_type': 'section'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.preset'),
        ),
    ]
