# Generated by Django 5.2.4 on 2025-11-26 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_preset_card_style_preset_contentblock_block_preset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycontainer',
            name='style_variant',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Preset 1'), (2, 'Preset 2'), (3, 'Preset 3'), (4, 'Preset 4'), (5, 'Preset 5')], default=1, help_text='Gallery style preset index (1–5).'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='style_variant',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Preset 1'), (2, 'Preset 2'), (3, 'Preset 3'), (4, 'Preset 4'), (5, 'Preset 5')], default=1, help_text='Hero style preset index (1–5).'),
        ),
        migrations.AddField(
            model_name='listcontainer',
            name='style_variant',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Preset 1'), (2, 'Preset 2'), (3, 'Preset 3'), (4, 'Preset 4'), (5, 'Preset 5')], default=1, help_text='List style preset index (1–5).'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='style_variant',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Preset 1'), (2, 'Preset 2'), (3, 'Preset 3'), (4, 'Preset 4'), (5, 'Preset 5')], default=1, help_text='News item style preset index (1–5).'),
        ),
        migrations.AddField(
            model_name='publicsection',
            name='style_variant',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Preset 1'), (2, 'Preset 2'), (3, 'Preset 3'), (4, 'Preset 4'), (5, 'Preset 5')], default=1, help_text='Section style preset index (1–5).'),
        ),
        migrations.CreateModel(
            name='HotelPublicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_style_variant', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Page Preset 1'), (2, 'Page Preset 2'), (3, 'Page Preset 3'), (4, 'Page Preset 4'), (5, 'Page Preset 5')], help_text='Optional global style preset index (1–5) applied to all sections.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_page', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Public Page',
                'verbose_name_plural': 'Hotel Public Pages',
            },
        ),
    ]
