# Generated by Django 5.2.4 on 2025-11-27 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_gallerycontainer_style_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='section_type',
            field=models.CharField(blank=True, choices=[('hero', 'Hero'), ('gallery', 'Gallery'), ('list', 'List'), ('news', 'News'), ('footer', 'Footer'), ('rooms', 'Rooms')], help_text="Required when target_type='section'.", max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='RoomsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle for the rooms section', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description text')),
                ('style_variant', models.PositiveSmallIntegerField(choices=[(1, 'Preset 1'), (2, 'Preset 2'), (3, 'Preset 3'), (4, 'Preset 4'), (5, 'Preset 5')], default=1, help_text='Rooms section style preset index (1–5).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_data', to='hotel.publicsection')),
            ],
            options={
                'verbose_name': 'Rooms Section',
                'verbose_name_plural': 'Rooms Sections',
            },
        ),
    ]
