# Generated by Django 5.2.4 on 2025-11-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_alter_preset_section_type_roomssection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='target_type',
            field=models.CharField(choices=[('section', 'Section'), ('card', 'Card'), ('image', 'Image'), ('news_block', 'News Block'), ('footer', 'Footer'), ('page_theme', 'Page Theme'), ('room_card', 'Room Card'), ('section_header', 'Section Header')], max_length=20),
        ),
    ]
