# Generated by Django 5.2.4 on 2025-11-30 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_alter_preset_target_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_warning_hours', models.DecimalField(decimal_places=2, default=6.0, help_text='Hours after which to send break warning notification', max_digits=4)),
                ('overtime_warning_hours', models.DecimalField(decimal_places=2, default=10.0, help_text='Hours after which to send overtime warning notification', max_digits=4)),
                ('hard_limit_hours', models.DecimalField(decimal_places=2, default=12.0, help_text='Maximum shift hours before requiring action from staff', max_digits=4)),
                ('enforce_limits', models.BooleanField(default=True, help_text='Whether to actively enforce attendance limits and warnings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Attendance Settings',
                'verbose_name_plural': 'Attendance Settings',
            },
        ),
    ]
