# Generated by Django 5.2.4 on 2025-11-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_attendancesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesettings',
            name='allow_face_self_registration',
            field=models.BooleanField(default=True, help_text='Allow staff to register their own face data'),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='face_attendance_departments',
            field=models.JSONField(default=list, help_text='List of department IDs that can use face attendance (empty = all)'),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='face_attendance_enabled',
            field=models.BooleanField(default=False, help_text='Enable face recognition for attendance tracking'),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='face_attendance_min_confidence',
            field=models.FloatField(default=0.8, help_text='Minimum confidence score for face recognition (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='face_data_retention_days',
            field=models.IntegerField(default=365, help_text='Number of days to retain face data after staff leaves'),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='require_face_consent',
            field=models.BooleanField(default=True, help_text='Require explicit consent before collecting face data'),
        ),
    ]
