# Generated by Django 5.2.4 on 2025-12-13 13:25

from django.db import migrations, models
import django.db.models.deletion


def migrate_guest_fields_to_primary(apps, schema_editor):
    """
    Migrate existing guest_* fields to primary_* fields
    """
    RoomBooking = apps.get_model('hotel', 'RoomBooking')
    
    for booking in RoomBooking.objects.all():
        # Copy guest fields to primary fields
        booking.primary_first_name = booking.guest_first_name or ''
        booking.primary_last_name = booking.guest_last_name or ''
        booking.primary_email = booking.guest_email or ''
        booking.primary_phone = booking.guest_phone or ''
        
        # Set booker_type to SELF since existing bookings were self-bookings
        booking.booker_type = 'SELF'
        
        booking.save()


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - copy primary fields back to guest fields
    """
    RoomBooking = apps.get_model('hotel', 'RoomBooking')
    
    for booking in RoomBooking.objects.all():
        booking.guest_first_name = booking.primary_first_name
        booking.guest_last_name = booking.primary_last_name
        booking.guest_email = booking.primary_email
        booking.guest_phone = booking.primary_phone
        booking.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0027_add_face_attendance_settings'),
        ('rooms', '0013_remove_room_guests'),
    ]

    operations = [
        # Add new fields with temporary defaults
        migrations.AddField(
            model_name='roombooking',
            name='booker_type',
            field=models.CharField(
                choices=[('SELF', 'Booker is staying'), ('THIRD_PARTY', 'Third-party (gift/agent)'), ('COMPANY', 'Company booking')],
                default='SELF',
                help_text='Relationship between booker and primary staying guest',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='booker_first_name',
            field=models.CharField(blank=True, help_text='Booker first name (if different from guest)', max_length=100),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='booker_last_name',
            field=models.CharField(blank=True, help_text='Booker last name (if different from guest)', max_length=100),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='booker_email',
            field=models.EmailField(blank=True, help_text='Booker email for payment/confirmation', max_length=254),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='booker_phone',
            field=models.CharField(blank=True, help_text='Booker contact phone', max_length=30),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='booker_company',
            field=models.CharField(blank=True, help_text='Company name for corporate bookings', max_length=150),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='primary_first_name',
            field=models.CharField(default='', help_text='Primary guest first name (person staying)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roombooking',
            name='primary_last_name',
            field=models.CharField(default='', help_text='Primary guest last name (person staying)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roombooking',
            name='primary_email',
            field=models.EmailField(blank=True, help_text='Primary guest email', max_length=254),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='primary_phone',
            field=models.CharField(blank=True, help_text='Primary guest contact phone', max_length=30),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='assigned_room',
            field=models.ForeignKey(blank=True, help_text='Room assigned during check-in process', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_bookings', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when guest checked in', null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when guest checked out', null=True),
        ),
        
        # Migrate data from old fields to new fields
        migrations.RunPython(migrate_guest_fields_to_primary, reverse_migration),
        
        # Remove old fields
        migrations.RemoveField(
            model_name='roombooking',
            name='guest_first_name',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='guest_last_name',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='guest_email',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='guest_phone',
        ),
        
        # Update indexes to use new field names
        migrations.AlterModelOptions(
            name='roombooking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Room Booking', 'verbose_name_plural': 'Room Bookings'},
        ),
        migrations.AlterIndexTogether(
            name='roombooking',
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name='roombooking',
            index=models.Index(fields=['hotel', 'check_in', 'check_out'], name='hotel_roomboo_hotel_i_a58e61_idx'),
        ),
        migrations.AddIndex(
            model_name='roombooking',
            index=models.Index(fields=['booking_id'], name='hotel_roomboo_booking_31e7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='roombooking',
            index=models.Index(fields=['primary_email'], name='hotel_roomboo_primary_3c1e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='roombooking',
            index=models.Index(fields=['status'], name='hotel_roomboo_status_8f7b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='roombooking',
            index=models.Index(fields=['assigned_room'], name='hotel_roomboo_assigne_4d2a1b_idx'),
        ),
    ]
