# Generated by Django 5.2.4 on 2025-12-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0028_migrate_booking_guest_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary Staying Guest'), ('COMPANION', 'Companion')], default='COMPANION', help_text='Role of this guest in the booking party', max_length=20)),
                ('first_name', models.CharField(help_text='Guest first name', max_length=100)),
                ('last_name', models.CharField(help_text='Guest last name', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Guest email (optional)', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Guest phone (optional)', max_length=30)),
                ('is_staying', models.BooleanField(default=True, help_text='Always true for party members - they are all staying guests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['role', 'created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='roombooking',
            name='hotel_roomb_guest_e_d67049_idx',
        ),
        migrations.RemoveIndex(
            model_name='roombooking',
            name='hotel_roomboo_hotel_i_a58e61_idx',
        ),
        migrations.RemoveIndex(
            model_name='roombooking',
            name='hotel_roomboo_booking_31e7e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='roombooking',
            name='hotel_roomboo_status_8f7b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='roombooking',
            new_name='hotel_roomb_primary_b8ea81_idx',
            old_name='hotel_roomboo_primary_3c1e2d_idx',
        ),
        migrations.RenameIndex(
            model_name='roombooking',
            new_name='hotel_roomb_assigne_08b493_idx',
            old_name='hotel_roomboo_assigne_4d2a1b_idx',
        ),
        migrations.AddField(
            model_name='bookingguest',
            name='booking',
            field=models.ForeignKey(help_text='The booking this guest belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='party', to='hotel.roombooking'),
        ),
        migrations.AddIndex(
            model_name='bookingguest',
            index=models.Index(fields=['booking', 'role'], name='hotel_booki_booking_91369f_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingguest',
            index=models.Index(fields=['booking', 'created_at'], name='hotel_booki_booking_02ad98_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingguest',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'PRIMARY')), fields=('booking',), name='unique_primary_per_booking'),
        ),
    ]
