# Generated by Django 5.2.4 on 2025-12-16 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0029_bookingguest_and_more'),
        ('staff', '0019_staff_is_on_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='assignment_notes',
            field=models.TextField(blank=True, help_text='Notes about room assignment'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='assignment_version',
            field=models.PositiveIntegerField(default=0, help_text='Assignment version for debugging concurrency issues'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room_assigned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when room was assigned', null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room_assigned_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who assigned the room', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_assignments', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room_reassigned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when room was last reassigned', null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room_reassigned_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who last reassigned the room', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_reassignments', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room_unassigned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when room was unassigned', null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room_unassigned_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who unassigned the room', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_unassignments', to='staff.staff'),
        ),
    ]
