# Generated by Django 5.2.4 on 2025-12-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_add_room_assignment_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPrecheckinToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA256 hash of the raw token', max_length=64)),
                ('expires_at', models.DateTimeField(help_text='Token expiry timestamp')),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when token was successfully used', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Timestamp when token was revoked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Token creation timestamp')),
                ('sent_to_email', models.EmailField(blank=True, help_text='Email address where link was sent (audit trail)', max_length=254)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precheckin_tokens', to='hotel.roombooking')),
            ],
            options={
                'db_table': 'hotel_booking_precheckin_token',
                'indexes': [models.Index(fields=['token_hash'], name='hotel_booki_token_h_9956fb_idx'), models.Index(fields=['expires_at'], name='hotel_booki_expires_274313_idx')],
            },
        ),
    ]
