# Generated by Django 5.2.4 on 2025-12-17 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0031_bookingprecheckintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingprecheckintoken',
            name='config_snapshot_enabled',
            field=models.JSONField(blank=True, default=dict, help_text="Snapshot of hotel's enabled fields at token creation time"),
        ),
        migrations.AddField(
            model_name='bookingprecheckintoken',
            name='config_snapshot_required',
            field=models.JSONField(blank=True, default=dict, help_text="Snapshot of hotel's required fields at token creation time"),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='precheckin_payload',
            field=models.JSONField(blank=True, default=dict, help_text="Extra precheckin data stored from hotel's field configuration"),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='precheckin_submitted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when guest completed precheckin submission', null=True),
        ),
        migrations.CreateModel(
            name='HotelPrecheckinConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields_enabled', models.JSONField(blank=True, default=dict, help_text='Dict of field_key: boolean for enabled precheckin fields')),
                ('fields_required', models.JSONField(blank=True, default=dict, help_text='Dict of field_key: boolean for required precheckin fields')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='precheckin_config', to='hotel.hotel')),
            ],
        ),
    ]
