# Generated by Django 5.2.4 on 2025-12-18 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0032_add_precheckin_config'),
        ('staff', '0001_initial'),  # Ensure staff app exists for ForeignKey
    ]

    operations = [
        # Add new fields to RoomBooking for authorization flow
        migrations.AddField(
            model_name='roombooking',
            name='payment_intent_id',
            field=models.CharField(
                blank=True, null=True, max_length=200, db_index=True,
                help_text="Stripe PaymentIntent ID for authorization/capture"
            ),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='payment_authorized_at',
            field=models.DateTimeField(
                blank=True, null=True,
                help_text="When payment was authorized (hold created)"
            ),
        ),
        
        # Add staff decision tracking fields
        migrations.AddField(
            model_name='roombooking',
            name='decision_by',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='booking_decisions', to='staff.staff'
            ),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='decline_reason_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='decline_reason_note',
            field=models.TextField(blank=True),
        ),
        
        # Add new booking statuses
        migrations.AlterField(
            model_name='roombooking',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING_PAYMENT', 'Pending Payment'),
                    ('PENDING_APPROVAL', 'Pending Staff Approval'),  # NEW
                    ('CONFIRMED', 'Confirmed'),
                    ('DECLINED', 'Declined'),  # NEW
                    ('CANCELLED', 'Cancelled'),
                    ('COMPLETED', 'Completed'),
                    ('NO_SHOW', 'No Show'),
                ],
                default='PENDING_PAYMENT',
                max_length=20
            ),
        ),
        
        # Create StripeWebhookEvent model for DB idempotency
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('checkout_session_id', models.CharField(blank=True, max_length=200)),
                ('payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('booking_id', models.CharField(blank=True, max_length=50, help_text="BK-2025-XXXX")),
                ('hotel_slug', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(
                    choices=[
                        ('PROCESSED', 'Successfully Processed'),
                        ('FAILED', 'Processing Failed'),
                    ],
                    default='PROCESSED',
                    max_length=20
                )),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stripe_webhook_events',
            },
        ),
        
        # Add indexes for StripeWebhookEvent
        migrations.RunSQL([
            "CREATE INDEX idx_stripe_webhook_booking ON stripe_webhook_events (booking_id, hotel_slug);",
            "CREATE INDEX idx_stripe_webhook_session ON stripe_webhook_events (checkout_session_id);", 
            "CREATE INDEX idx_stripe_webhook_intent ON stripe_webhook_events (payment_intent_id);",
            "CREATE INDEX idx_stripe_webhook_processed ON stripe_webhook_events (processed_at);",
        ], reverse_sql=[
            "DROP INDEX idx_stripe_webhook_booking;",
            "DROP INDEX idx_stripe_webhook_session;",
            "DROP INDEX idx_stripe_webhook_intent;", 
            "DROP INDEX idx_stripe_webhook_processed;",
        ]),
    ]
