# Generated by Django 5.2.4 on 2025-12-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0033_auto_20251218_1520'),
    ]

    operations = [
    ]
