# Generated by Django 5.2.4 on 2025-12-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0034_auto_20251218_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeWebhookEvent',
        ),
    ]
