# Generated by Django 5.2.4 on 2025-12-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0035_delete_stripewebhookevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='decline_reason_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='decline_reason_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
