# Generated by Django 5.2.4 on 2025-12-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0036_alter_decline_fields_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Stripe event ID', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text='Stripe event type', max_length=100)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=20)),
                ('checkout_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_id', models.CharField(blank=True, max_length=50, null=True)),
                ('hotel_slug', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hotel_stripe_webhook_event',
                'indexes': [models.Index(fields=['event_id'], name='hotel_strip_event_i_e38ed8_idx'), models.Index(fields=['event_type'], name='hotel_strip_event_t_5eab8d_idx'), models.Index(fields=['status'], name='hotel_strip_status_05fce7_idx'), models.Index(fields=['created_at'], name='hotel_strip_created_bf8560_idx')],
            },
        ),
    ]
