# Generated by Django 5.2.4 on 2025-12-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0037_add_stripe_webhook_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingguest',
            name='precheckin_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Guest-specific precheckin data (nationality, country_of_residence, etc.)'),
        ),
    ]
