# Generated by Django 5.2.4 on 2025-12-23 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0038_bookingguest_precheckin_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='survey_last_sent_to',
            field=models.EmailField(blank=True, help_text='Email address where survey was last sent (audit trail)', max_length=254),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='survey_send_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled time for delayed survey sending', null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='survey_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when survey email was sent (idempotency tracking)', null=True),
        ),
        migrations.CreateModel(
            name='BookingSurveyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA256 hash of the raw token', max_length=64)),
                ('expires_at', models.DateTimeField(help_text='Token expiry timestamp')),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when token was successfully used', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Timestamp when token was revoked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Token creation timestamp')),
                ('sent_to_email', models.EmailField(blank=True, help_text='Email address where link was sent (audit trail)', max_length=254)),
                ('config_snapshot_enabled', models.JSONField(blank=True, default=dict, help_text="Snapshot of hotel's enabled fields at token creation time")),
                ('config_snapshot_required', models.JSONField(blank=True, default=dict, help_text="Snapshot of hotel's required fields at token creation time")),
                ('config_snapshot_send_mode', models.CharField(blank=True, help_text='Snapshot of send mode at token creation time', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_tokens', to='hotel.roombooking')),
            ],
            options={
                'verbose_name': 'Booking Survey Token',
                'verbose_name_plural': 'Booking Survey Tokens',
                'db_table': 'hotel_booking_survey_token',
            },
        ),
        migrations.CreateModel(
            name='BookingSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict, help_text='Full survey response data')),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, help_text='Overall rating extracted for analytics (1-5)', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Survey submission timestamp')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_response', to='hotel.roombooking')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='hotel.hotel')),
                ('token_used', models.ForeignKey(help_text='Token that was used to submit this survey (audit trail)', on_delete=django.db.models.deletion.CASCADE, to='hotel.bookingsurveytoken')),
            ],
            options={
                'verbose_name': 'Booking Survey Response',
                'verbose_name_plural': 'Booking Survey Responses',
                'db_table': 'hotel_booking_survey_response',
            },
        ),
        migrations.CreateModel(
            name='HotelSurveyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields_enabled', models.JSONField(blank=True, default=dict, help_text='Dict of field_key: boolean for enabled survey fields')),
                ('fields_required', models.JSONField(blank=True, default=dict, help_text='Dict of field_key: boolean for required survey fields')),
                ('send_mode', models.CharField(choices=[('AUTO_IMMEDIATE', 'Send immediately after checkout'), ('AUTO_DELAYED', 'Send after delay'), ('MANUAL_ONLY', 'Manual sending only')], default='AUTO_DELAYED', help_text='Survey email sending policy', max_length=20)),
                ('delay_hours', models.PositiveIntegerField(default=24, help_text='Hours to delay survey email after checkout (for AUTO_DELAYED mode)')),
                ('token_expiry_hours', models.PositiveIntegerField(default=168, help_text='Survey token expiry time in hours')),
                ('email_subject_template', models.TextField(blank=True, help_text='Optional custom email subject template')),
                ('email_body_template', models.TextField(blank=True, help_text='Optional custom email body template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_config', to='hotel.hotel')),
            ],
        ),
        migrations.AddIndex(
            model_name='bookingsurveytoken',
            index=models.Index(fields=['token_hash'], name='hotel_booki_token_h_4f9a04_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingsurveytoken',
            index=models.Index(fields=['booking'], name='hotel_booki_booking_f1292c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingsurveytoken',
            index=models.Index(fields=['expires_at'], name='hotel_booki_expires_1ce145_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingsurveytoken',
            index=models.Index(fields=['used_at'], name='hotel_booki_used_at_045f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingsurveyresponse',
            index=models.Index(fields=['hotel', 'submitted_at'], name='hotel_booki_hotel_i_761d56_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingsurveyresponse',
            index=models.Index(fields=['booking'], name='hotel_booki_booking_5bd63d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingsurveyresponse',
            index=models.Index(fields=['overall_rating'], name='hotel_booki_overall_a4d8dd_idx'),
        ),
    ]
