# Generated by Django 5.2.4 on 2025-12-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0039_add_survey_models'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookingsurveyresponse',
            constraint=models.UniqueConstraint(fields=('booking',), name='unique_survey_per_booking', violation_error_message='Only one survey response allowed per booking'),
        ),
    ]
