# Generated by Django 5.2.4 on 2025-12-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0040_add_survey_constraints'),
    ]

    operations = [
    ]
