# Generated by Django 5.2.4 on 2025-12-23 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0041_survey_operational_intelligence'),
        ('rooms', '0016_convert_available_to_ready_for_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='cancellation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee charged for cancellation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='cancellation_reason',
            field=models.CharField(blank=True, help_text='Reason for cancellation', max_length=255),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when booking was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='rate_plan',
            field=models.ForeignKey(blank=True, help_text='Rate plan used for this booking (for policy/price debugging)', null=True, on_delete=django.db.models.deletion.PROTECT, to='rooms.rateplan'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount refunded to guest', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when refund was processed (idempotency guard)', null=True),
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Policy name (e.g., 'Flexible Cancellation')", max_length=100)),
                ('code', models.CharField(help_text="Short code (e.g., 'FLEX', 'NRF', 'MOD')", max_length=30)),
                ('description', models.TextField(blank=True, help_text='Policy description for guests')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this policy is available for selection')),
                ('template_type', models.CharField(choices=[('FLEXIBLE', 'Flexible'), ('MODERATE', 'Moderate'), ('NON_REFUNDABLE', 'Non-Refundable'), ('CUSTOM', 'Custom Tiered')], help_text='Policy template type', max_length=20)),
                ('free_until_hours', models.PositiveIntegerField(blank=True, help_text='Hours before check-in when free cancellation ends', null=True)),
                ('penalty_type', models.CharField(blank=True, choices=[('NONE', 'No Penalty'), ('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage'), ('FIRST_NIGHT', 'First Night'), ('FULL_STAY', 'Full Stay')], help_text='Type of penalty to apply', max_length=20, null=True)),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed penalty amount (for FIXED penalty type)', max_digits=10, null=True)),
                ('penalty_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Penalty percentage of total amount (for PERCENTAGE penalty type)', max_digits=5, null=True)),
                ('no_show_penalty_type', models.CharField(choices=[('SAME_AS_CANCELLATION', 'Same as Cancellation'), ('FIRST_NIGHT', 'First Night'), ('FULL_STAY', 'Full Stay')], default='FULL_STAY', help_text='Penalty type for no-show situations', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policies', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Cancellation Policy',
                'verbose_name_plural': 'Cancellation Policies',
                'ordering': ['hotel', 'name'],
                'unique_together': {('hotel', 'code')},
            },
        ),
        migrations.AddField(
            model_name='roombooking',
            name='cancellation_policy',
            field=models.ForeignKey(blank=True, help_text='Snapshot of cancellation policy at booking time', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.cancellationpolicy'),
        ),
        migrations.CreateModel(
            name='CancellationPolicyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_before_checkin', models.PositiveIntegerField(help_text='Hours before check-in when this tier applies')),
                ('penalty_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage'), ('FIRST_NIGHT', 'First Night'), ('FULL_STAY', 'Full Stay')], help_text='Type of penalty for this tier', max_length=20)),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed penalty amount (for FIXED penalty type)', max_digits=10, null=True)),
                ('penalty_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Penalty percentage of total amount (for PERCENTAGE penalty type)', max_digits=5, null=True)),
                ('policy', models.ForeignKey(help_text='The cancellation policy this tier belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='hotel.cancellationpolicy')),
            ],
            options={
                'verbose_name': 'Cancellation Policy Tier',
                'verbose_name_plural': 'Cancellation Policy Tiers',
                'ordering': ['-hours_before_checkin'],
                'constraints': [models.UniqueConstraint(fields=('policy', 'hours_before_checkin'), name='uniq_policy_hours', violation_error_message='Cannot have duplicate hour thresholds for the same policy.')],
            },
        ),
    ]
