# Generated by Django 5.2.4 on 2025-12-24 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0042_add_cancellation_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='default_cancellation_policy',
            field=models.ForeignKey(blank=True, help_text="Default cancellation policy for new bookings when rate plans don't have policies", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels_using_as_default', to='hotel.cancellationpolicy'),
        ),
    ]
