# Generated by Django 5.2.4 on 2025-12-26 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0043_add_default_cancellation_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingManagementToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA256 hash of the raw token', max_length=64)),
                ('expires_at', models.DateTimeField(help_text='Token expiry timestamp')),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when token was successfully used for cancellation', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Timestamp when token was revoked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Token creation timestamp')),
                ('sent_to_email', models.EmailField(blank=True, help_text='Email address where management link was sent (audit trail)', max_length=254)),
                ('actions_performed', models.JSONField(blank=True, default=list, help_text='List of actions performed with this token (view, cancel, etc.)')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_tokens', to='hotel.roombooking')),
            ],
            options={
                'db_table': 'hotel_booking_management_token',
                'indexes': [models.Index(fields=['token_hash'], name='hotel_booki_token_h_cdda09_idx'), models.Index(fields=['expires_at'], name='hotel_booki_expires_2743c8_idx')],
            },
        ),
    ]
