# Generated by Django 5.2.4 on 2025-12-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0044_bookingmanagementtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='refund_reference',
            field=models.CharField(blank=True, default='', help_text='Stripe refund ID or other payment provider refund reference', max_length=255),
        ),
    ]
