# Generated by Django 5.2.4 on 2025-12-26 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0045_add_refund_reference_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBookingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the actual token', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Token expiration (recommended: check_out + 30 days)', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When token was revoked (for security/cancellation)', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time token was used (for debugging/security)', null=True)),
                ('purpose', models.CharField(choices=[('STATUS', 'Booking Status Access'), ('PRECHECKIN', 'Pre-checkin Process')], default='STATUS', help_text='Token purpose for future extensibility', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_tokens', to='hotel.roombooking')),
                ('hotel', models.ForeignKey(help_text='Derived from booking.hotel for query optimization', on_delete=django.db.models.deletion.CASCADE, related_name='guest_booking_tokens', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Guest Booking Token',
                'verbose_name_plural': 'Guest Booking Tokens',
                'indexes': [models.Index(fields=['token_hash'], name='hotel_guest_token_h_a99689_idx'), models.Index(fields=['booking'], name='hotel_guest_booking_c9fcea_idx'), models.Index(fields=['hotel'], name='hotel_guest_hotel_i_9f50e7_idx'), models.Index(fields=['expires_at'], name='hotel_guest_expires_874ab5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('booking',), name='one_active_token_per_booking')],
            },
        ),
    ]
