# Generated by Django 5.2.4 on 2025-12-29 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0046_add_guest_booking_token'),
        ('rooms', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='room_moved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when room was moved', null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room_moved_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who moved the room', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_moves_made', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room_moved_from',
            field=models.ForeignKey(blank=True, help_text='Room moved from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_moves_from', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room_move_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for room move'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room_move_notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes about room move'),
        ),
    ]
