# Generated by Django 5.2.4 on 2025-12-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0048_add_booking_expiration_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roombooking',
            new_name='hotel_roomb_expires_d54b79_idx',
            old_name='hotel_roombooking_expires_at_idx',
        ),
    ]
