# Generated by Django 5.2.4 on 2025-12-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0049_rename_hotel_roombooking_expires_at_idx_hotel_roomb_expires_d54b79_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guestbookingtoken',
            name='one_active_token_per_booking',
        ),
        migrations.AddField(
            model_name='guestbookingtoken',
            name='revoked_reason',
            field=models.CharField(blank=True, help_text='Reason for token revocation (CHECKOUT/CANCELLED/SECURITY)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guestbookingtoken',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', help_text='Token status for lifecycle management', max_length=10),
        ),
        migrations.AlterField(
            model_name='guestbookingtoken',
            name='purpose',
            field=models.CharField(choices=[('STATUS', 'Booking Status Access'), ('PRECHECKIN', 'Pre-checkin Process'), ('CHAT', 'Guest Chat Messages'), ('ROOM_SERVICE', 'Room Service Orders'), ('FULL_ACCESS', 'Full Guest Portal Access')], default='STATUS', help_text='Token purpose for future extensibility', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='guestbookingtoken',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('booking',), name='one_active_token_per_booking'),
        ),
    ]
