# Generated by Django 5.2.4 on 2026-01-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0050_remove_guestbookingtoken_one_active_token_per_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookingtoken',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text="Token capabilities: ['STATUS_READ', 'CHAT', 'ROOM_SERVICE']"),
        ),
    ]
