# Generated by Django 5.2.4 on 2026-01-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0051_add_scopes_to_guestbookingtoken'),
        ('rooms', '0017_add_cancellation_policies'),
        ('staff', '0019_staff_is_on_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelaccessconfig',
            name='approval_sla_minutes',
            field=models.PositiveIntegerField(default=30, help_text='SLA minutes for staff to approve paid bookings (PENDING_APPROVAL)'),
        ),
        migrations.AddField(
            model_name='hotelaccessconfig',
            name='late_checkout_grace_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Grace period after checkout time before overstay flagging'),
        ),
        migrations.AddField(
            model_name='hotelaccessconfig',
            name='standard_checkout_time',
            field=models.TimeField(default='11:00', help_text='Standard checkout time (e.g., 11:00 AM)'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='approval_deadline_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Deadline for staff to approve this booking (for PENDING_APPROVAL)', null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='auto_expire_reason_code',
            field=models.CharField(blank=True, default='', help_text='Reason code for automatic expiry (e.g., APPROVAL_TIMEOUT)', max_length=50),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='expired_at',
            field=models.DateTimeField(blank=True, help_text='When this booking was automatically expired due to timeout', null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='overstay_acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When staff acknowledged the overstay situation', null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='overstay_flagged_at',
            field=models.DateTimeField(blank=True, help_text='When this booking was flagged for overstay (past checkout deadline)', null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='When refund was processed', null=True),
        ),
        migrations.AddIndex(
            model_name='roombooking',
            index=models.Index(fields=['hotel', 'status', 'approval_deadline_at'], name='hotel_roomb_hotel_i_871edc_idx'),
        ),
        migrations.AddIndex(
            model_name='roombooking',
            index=models.Index(fields=['hotel', 'status', 'check_out'], name='hotel_roomb_hotel_i_1a1d4c_idx'),
        ),
    ]
