# Generated by Django 5.2.4 on 2026-01-20 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0053_add_expired_status'),
        ('staff', '0019_staff_is_on_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='staff_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when any staff member first viewed this booking', null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='staff_seen_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who first viewed this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seen_room_bookings', to='staff.staff'),
        ),
    ]
