# Generated by Django 5.2.4 on 2026-01-23 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0054_add_staff_seen_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='timezone',
            field=models.CharField(default='Europe/Dublin', help_text='IANA timezone string (e.g., Europe/Dublin, America/New_York)', max_length=50),
        ),
        migrations.CreateModel(
            name='BookingExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('old_checkout_date', models.DateField()),
                ('new_checkout_date', models.DateField()),
                ('added_nights', models.PositiveSmallIntegerField()),
                ('pricing_snapshot', models.JSONField()),
                ('amount_delta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('idempotency_key', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING_PAYMENT', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.roombooking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'indexes': [models.Index(fields=['hotel', 'created_at'], name='hotel_booki_hotel_i_f7aa4d_idx'), models.Index(fields=['booking'], name='hotel_booki_booking_a7e830_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('booking', 'idempotency_key'), name='unique_idempotency_per_booking')],
            },
        ),
        migrations.CreateModel(
            name='OverstayIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('expected_checkout_date', models.DateField()),
                ('detected_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_reason', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_overstays', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.roombooking')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_overstays', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_overstays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['hotel', 'status'], name='hotel_overs_hotel_i_7da673_idx'), models.Index(fields=['detected_at'], name='hotel_overs_detecte_4dc864_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'ACKED'])), fields=('booking',), name='unique_active_overstay_per_booking')],
            },
        ),
    ]
