# Generated by Django 5.2.4 on 2026-01-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0055_hotel_timezone_bookingextension_overstayincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PENDING_APPROVAL', 'Pending Staff Approval'), ('CONFIRMED', 'Confirmed'), ('IN_HOUSE', 'In House'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('CANCELLED_DRAFT', 'Cancelled Draft'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='PENDING_PAYMENT', max_length=20),
        ),
    ]
