# Generated by Django 5.2.4 on 2026-01-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0056_alter_roombooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelaccessconfig',
            name='approval_cutoff_day_offset',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Same day'), (1, 'Next day')], default=0, help_text='Day offset: 0=check-in day, 1=day after check-in'),
        ),
        migrations.AddField(
            model_name='hotelaccessconfig',
            name='approval_cutoff_time',
            field=models.TimeField(default='22:00', help_text='Daily cutoff time for booking approval (e.g., 22:00)'),
        ),
    ]
