# Generated by Django 5.2.4 on 2026-01-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0057_hotelaccessconfig_approval_cutoff_day_offset_and_more'),
    ]

    operations = [
        # Add performance indexes for booking list filtering
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS hotel_roombooking_hotel_primary_first_name_idx ON hotel_roombooking (hotel_id, primary_first_name);",
            reverse_sql="DROP INDEX IF EXISTS hotel_roombooking_hotel_primary_first_name_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS hotel_roombooking_hotel_primary_last_name_idx ON hotel_roombooking (hotel_id, primary_last_name);",
            reverse_sql="DROP INDEX IF EXISTS hotel_roombooking_hotel_primary_last_name_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS hotel_roombooking_hotel_booker_first_name_idx ON hotel_roombooking (hotel_id, booker_first_name);",
            reverse_sql="DROP INDEX IF EXISTS hotel_roombooking_hotel_booker_first_name_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS hotel_roombooking_hotel_booker_last_name_idx ON hotel_roombooking (hotel_id, booker_last_name);",
            reverse_sql="DROP INDEX IF EXISTS hotel_roombooking_hotel_booker_last_name_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS hotel_roombooking_hotel_booker_email_idx ON hotel_roombooking (hotel_id, booker_email);",
            reverse_sql="DROP INDEX IF EXISTS hotel_roombooking_hotel_booker_email_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS hotel_roombooking_hotel_checked_in_at_idx ON hotel_roombooking (hotel_id, checked_in_at);",
            reverse_sql="DROP INDEX IF EXISTS hotel_roombooking_hotel_checked_in_at_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS hotel_roombooking_hotel_checked_out_at_idx ON hotel_roombooking (hotel_id, checked_out_at);",
            reverse_sql="DROP INDEX IF EXISTS hotel_roombooking_hotel_checked_out_at_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS hotel_roombooking_hotel_room_type_idx ON hotel_roombooking (hotel_id, room_type_id);",
            reverse_sql="DROP INDEX IF EXISTS hotel_roombooking_hotel_room_type_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS hotel_roombooking_hotel_adults_children_idx ON hotel_roombooking (hotel_id, adults, children);",
            reverse_sql="DROP INDEX IF EXISTS hotel_roombooking_hotel_adults_children_idx;"
        ),
    ]
