# Generated by Django 5.2.4 on 2025-10-25 10:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0003_memorygameachievement_memorygamestats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryGameCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Card name/identifier (e.g., 'alien', 'fox', 'smiley')", max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('image', cloudinary.models.CloudinaryField(help_text='Card image file', max_length=255, verbose_name='memory_card_image')),
                ('description', models.TextField(blank=True, help_text='Optional description of the card')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this card is available for games')),
                ('difficulty_levels', models.CharField(default='easy,intermediate,hard', help_text='Comma-separated difficulty levels where this card appears', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='entertainme_is_acti_2b43eb_idx'), models.Index(fields=['slug'], name='entertainme_slug_b8f568_idx')],
            },
        ),
        migrations.AddField(
            model_name='memorygamesession',
            name='cards_used',
            field=models.ManyToManyField(blank=True, help_text='Cards that were used in this game session', related_name='game_sessions', to='entertainment.memorygamecard'),
        ),
    ]
