# Generated by Django 5.2.4 on 2025-10-27 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0004_memorygamecard_memorygamesession_cards_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memorygamesession',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='True if this is an anonymous kids tournament entry'),
        ),
        migrations.AddField(
            model_name='memorygamesession',
            name='player_name',
            field=models.CharField(blank=True, help_text="Anonymous player name (e.g., 'Player 1234')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memorygamesession',
            name='room_number',
            field=models.CharField(blank=True, help_text="Room number or 'Kids Tournament' for anonymous", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='memorygamesession',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Registered user (optional for anonymous players)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_game_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
