# Generated by Django 5.2.4 on 2025-10-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0005_memorygamesession_is_anonymous_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorygametournament',
            name='difficulty',
        ),
    ]
