# Generated by Django 5.2.4 on 2025-10-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0006_remove_memorygametournament_difficulty'),
        ('hotel', '0004_alter_hotel_logo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='memorygamesession',
            name='entertainme_user_id_45dd87_idx',
        ),
        migrations.RemoveField(
            model_name='memorygamesession',
            name='user',
        ),
        migrations.AlterField(
            model_name='memorygamesession',
            name='player_name',
            field=models.CharField(default='Anonymous Player', help_text="Anonymous player name with token (e.g., 'Alice|player_123')", max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='memorygamesession',
            index=models.Index(fields=['player_name', 'difficulty'], name='entertainme_player__5b576c_idx'),
        ),
    ]
