# Generated by Django 5.2.4 on 2025-11-13 17:46

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0007_remove_memorygamesession_entertainme_user_id_45dd87_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Quiz Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='entertainme_is_acti_3825ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Classic Trivia (Easy)'), (2, 'Odd One Out (Moderate)'), (3, 'Fill the Blank (Challenging)'), (4, 'Dynamic Math (Mid-Hard)'), (5, 'Knowledge Trap (Hard)')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_daily', models.BooleanField(default=False, help_text='Mark as daily quiz (featured)')),
                ('max_questions', models.PositiveIntegerField(default=10, help_text='Maximum number of questions in this quiz')),
                ('time_per_question_seconds', models.PositiveIntegerField(blank=True, help_text='Time per question (default based on difficulty: L1=20, L2=18, L3=15, L4=12, L5=10)', null=True)),
                ('total_time_limit_seconds', models.PositiveIntegerField(blank=True, help_text='Optional total time limit for entire quiz', null=True)),
                ('enable_background_music', models.BooleanField(default=True)),
                ('enable_sound_effects', models.BooleanField(default=True)),
                ('sound_theme', models.CharField(choices=[('default', 'Default'), ('tense', 'Tense'), ('chill', 'Chill')], default='default', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='entertainment.quizcategory')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'ordering': ['difficulty_level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Question text')),
                ('image_url', cloudinary.models.CloudinaryField(blank=True, help_text='Optional image for question', max_length=255, null=True, verbose_name='quiz_question_image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('base_points', models.PositiveIntegerField(default=10, help_text='Base points for correct answer (reduced by time taken)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='entertainment.quiz')),
            ],
            options={
                'ordering': ['quiz', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False, help_text='Mark as the correct answer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in answer list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='entertainment.quizquestion')),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hotel_identifier', models.CharField(help_text='Hotel identifier from QR code (hotel slug)', max_length=100)),
                ('player_name', models.CharField(help_text="Player's display name", max_length=100)),
                ('external_player_id', models.CharField(blank=True, help_text='Optional external player identifier (e.g., room number, device ID)', max_length=100, null=True)),
                ('score', models.IntegerField(default=0, help_text='Total accumulated score')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, help_text='Total time spent on quiz')),
                ('current_question_index', models.PositiveIntegerField(default=0, help_text='Index of current question (0-based)')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='entertainment.quiz')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hotel_identifier', models.CharField(help_text='Hotel identifier from QR code', max_length=100)),
                ('question_text', models.TextField(blank=True, help_text='Question text (for math or reference)')),
                ('question_data', models.JSONField(blank=True, help_text='Additional question data (e.g., math operands, correct answer)', null=True)),
                ('selected_answer', models.CharField(help_text='Text of selected answer', max_length=500)),
                ('selected_answer_id', models.PositiveIntegerField(blank=True, help_text='ID of selected QuizAnswer (null for math)', null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('base_points', models.PositiveIntegerField(default=10, help_text='Base points for this question')),
                ('points_awarded', models.IntegerField(default=0, help_text='Actual points awarded (base minus time penalty)')),
                ('time_taken_seconds', models.PositiveIntegerField(default=0, help_text='Time taken to answer (seconds)')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, help_text='Null for dynamic math questions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='entertainment.quizquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='entertainment.quizsession')),
            ],
            options={
                'ordering': ['session', 'answered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_active', 'difficulty_level'], name='entertainme_is_acti_6b9d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_daily', 'is_active'], name='entertainme_is_dail_a88178_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['slug'], name='entertainme_slug_ddad8c_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz', 'is_active', 'order'], name='entertainme_quiz_id_09dc27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'order')},
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['question', 'is_correct'], name='entertainme_questio_6818ef_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['hotel_identifier', 'quiz', '-started_at'], name='entertainme_hotel_i_b4a5c8_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['quiz', '-score'], name='entertainme_quiz_id_55d123_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['is_completed', '-started_at'], name='entertainme_is_comp_0ab0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['session', 'answered_at'], name='entertainme_session_a45454_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['hotel_identifier', '-points_awarded'], name='entertainme_hotel_i_0083e6_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['is_correct'], name='entertainme_is_corr_468559_idx'),
        ),
    ]
