# Generated by Django 5.2.4 on 2025-11-14 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0007_remove_memorygamesession_entertainme_user_id_45dd87_idx_and_more'),
        ('hotel', '0004_alter_hotel_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'History', 'Science', 'Sports')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the category')),
                ('icon', models.CharField(blank=True, help_text='Icon/emoji for the category', max_length=50)),
                ('color', models.CharField(default='#4F46E5', help_text='Hex color code for UI', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is available for slot machine selection')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display in admin/UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Quiz Categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='entertainme_is_acti_99cb38_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question text')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Question difficulty level', max_length=6)),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='The correct option (A, B, C, or D)', max_length=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation of the correct answer')),
                ('points', models.PositiveIntegerField(default=10, help_text='Base points for this question')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is available for quizzes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='entertainment.quizcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'difficulty', 'question_text'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(help_text="Player name with token: 'PlayerName|token' (e.g., 'Alice|player_abc123')", max_length=150)),
                ('selected_categories', models.JSONField(help_text='List of category IDs selected for this quiz (5 random from 10)')),
                ('total_questions', models.PositiveIntegerField(default=0, help_text='Total number of questions in this quiz')),
                ('correct_answers', models.PositiveIntegerField(default=0, help_text='Number of correct answers')),
                ('score', models.IntegerField(default=0, help_text='Final calculated score')),
                ('time_seconds', models.PositiveIntegerField(blank=True, help_text='Total time taken in seconds', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Whether the quiz was completed')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the quiz was completed', null=True)),
                ('current_question_index', models.PositiveIntegerField(default=0, help_text='Current question index (for resuming)')),
                ('session_state', models.JSONField(blank=True, help_text='Additional state data for resuming quiz', null=True)),
                ('hotel', models.ForeignKey(blank=True, help_text='Hotel where quiz was played (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.hotel')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(help_text="Player name with token: 'PlayerName|token'", max_length=150)),
                ('player_token', models.CharField(help_text='Unique player token extracted from player_name', max_length=100, unique=True)),
                ('best_score', models.IntegerField(help_text="Player's best score across all casual play sessions")),
                ('total_games_played', models.PositiveIntegerField(default=1, help_text='Total number of casual games played')),
                ('first_played_at', models.DateTimeField(auto_now_add=True)),
                ('last_played_at', models.DateTimeField(auto_now=True)),
                ('best_score_achieved_at', models.DateTimeField(help_text='When the best score was achieved')),
                ('best_session', models.ForeignKey(help_text='Session where best score was achieved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaderboard_entries', to='entertainment.quizsession')),
            ],
            options={
                'ordering': ['-best_score'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text="Player's selected answer (A, B, C, or D)", max_length=1)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether the answer is correct')),
                ('time_seconds', models.PositiveIntegerField(blank=True, help_text='Time taken to answer this question (seconds)', null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(help_text='Question being answered', on_delete=django.db.models.deletion.CASCADE, related_name='player_answers', to='entertainment.quizquestion')),
                ('session', models.ForeignKey(help_text='Quiz session this answer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='entertainment.quizsession')),
            ],
            options={
                'ordering': ['session', 'answered_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tournament name', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Tournament description and rules')),
                ('max_participants', models.PositiveIntegerField(default=100, help_text='Maximum number of participants')),
                ('questions_per_quiz', models.PositiveIntegerField(default=20, help_text='Total questions per quiz session')),
                ('min_age', models.PositiveIntegerField(blank=True, help_text='Minimum age for participation', null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, help_text='Maximum age for participation', null=True)),
                ('start_date', models.DateTimeField(help_text='Tournament start date/time')),
                ('end_date', models.DateTimeField(help_text='Tournament end date/time')),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='Last date for registration (optional)', null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=10)),
                ('qr_code_url', models.URLField(blank=True, help_text='QR code URL for tournament access', null=True)),
                ('qr_generated_at', models.DateTimeField(blank=True, null=True)),
                ('first_prize', models.CharField(blank=True, help_text='First place prize', max_length=200)),
                ('second_prize', models.CharField(blank=True, help_text='Second place prize', max_length=200)),
                ('third_prize', models.CharField(blank=True, help_text='Third place prize', max_length=200)),
                ('rules', models.TextField(blank=True, help_text='Tournament rules and regulations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quiz_tournaments', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(blank=True, help_text='Hotel hosting this tournament (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_tournaments', to='hotel.hotel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quizsession',
            name='tournament',
            field=models.ForeignKey(blank=True, help_text='Tournament this session belongs to (null for casual play)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='entertainment.quiztournament'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['category', 'is_active'], name='entertainme_categor_a2c62b_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['difficulty', 'is_active'], name='entertainme_difficu_067a26_idx'),
        ),
        migrations.AddIndex(
            model_name='quizleaderboard',
            index=models.Index(fields=['-best_score'], name='entertainme_best_sc_21bde3_idx'),
        ),
        migrations.AddIndex(
            model_name='quizleaderboard',
            index=models.Index(fields=['player_token'], name='entertainme_player__ac58bd_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['session', 'is_correct'], name='entertainme_session_5be50e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('session', 'question')},
        ),
        migrations.AddIndex(
            model_name='quiztournament',
            index=models.Index(fields=['status', 'start_date'], name='entertainme_status_3d3ade_idx'),
        ),
        migrations.AddIndex(
            model_name='quiztournament',
            index=models.Index(fields=['hotel', 'status'], name='entertainme_hotel_i_5796ea_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['player_name', 'completed'], name='entertainme_player__bac45d_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['tournament', 'score'], name='entertainme_tournam_9acdf8_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['completed', '-score'], name='entertainme_complet_add236_idx'),
        ),
    ]
