# Generated by Django 5.2.4 on 2025-11-13 23:02

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0007_remove_memorygamesession_entertainme_user_id_45dd87_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('questions_per_category', models.PositiveIntegerField(default=10, help_text='How many questions from each category (default: 10)')),
                ('time_per_question_seconds', models.PositiveIntegerField(default=5, help_text='Time limit per question in seconds')),
                ('turbo_mode_threshold', models.PositiveIntegerField(default=5, help_text='Consecutive correct answers needed for turbo mode')),
                ('turbo_multiplier', models.DecimalField(decimal_places=1, default=2.0, help_text='Score multiplier in turbo mode (default: 2x)', max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_code_url', models.URLField(blank=True, null=True)),
                ('qr_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='temp-slug', max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in game (categories played in order)')),
                ('is_math_category', models.BooleanField(default=False, help_text='True for dynamic math category (generates questions)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Quiz Categories',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='entertainme_is_acti_2b71ec_idx'), models.Index(fields=['slug'], name='entertainme_slug_bd6093_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Question text')),
                ('image_url', cloudinary.models.CloudinaryField(blank=True, help_text='Optional image for question', max_length=255, null=True, verbose_name='quiz_question_image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='entertainment.quizcategory')),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='entertainment.quizquestion')),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(blank=True, help_text='Unique session token to identify player across games', max_length=255, null=True, unique=True)),
                ('player_name', models.CharField(help_text="Player's display name", max_length=100)),
                ('is_tournament_mode', models.BooleanField(default=False, help_text='Tournament mode vs Casual mode')),
                ('score', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('consecutive_correct', models.PositiveIntegerField(default=0, help_text='Consecutive correct answers')),
                ('is_turbo_active', models.BooleanField(default=False, help_text='Whether turbo mode is currently active')),
                ('current_category_index', models.PositiveIntegerField(default=0, help_text='Which category player is on (0-4)')),
                ('current_question_index', models.PositiveIntegerField(default=0, help_text='Which question within category (0-9)')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='entertainment.quiz')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=255)),
                ('player_name', models.CharField(max_length=100)),
                ('best_score', models.IntegerField()),
                ('games_played', models.PositiveIntegerField(default=1)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='entertainment.quiz')),
                ('best_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='entertainment.quizsession')),
            ],
            options={
                'ordering': ['-best_score', 'last_played'],
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(default='Question')),
                ('question_data', models.JSONField(blank=True, help_text='Math question data: operands, operator, correct_answer', null=True)),
                ('selected_answer', models.CharField(default='Answer', max_length=500)),
                ('selected_answer_id', models.PositiveIntegerField(blank=True, help_text='QuizAnswer ID (null for math)', null=True)),
                ('correct_answer', models.CharField(default='Answer', help_text='The correct answer (for comparison)', max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('was_turbo_active', models.BooleanField(default=False, help_text='Was turbo mode active for this answer?')),
                ('points_awarded', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='entertainment.quizcategory')),
                ('question', models.ForeignKey(blank=True, help_text='Null for math questions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='entertainment.quizquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='entertainment.quizsession')),
            ],
            options={
                'ordering': ['session', 'answered_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(help_text='Automatically set to 24 hours after start')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=10)),
                ('first_prize', models.CharField(blank=True, max_length=200)),
                ('second_prize', models.CharField(blank=True, max_length=200)),
                ('third_prize', models.CharField(blank=True, max_length=200)),
                ('qr_code_url', models.URLField(blank=True, null=True)),
                ('qr_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='entertainment.quiz')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='quizsession',
            name='tournament',
            field=models.ForeignKey(blank=True, help_text='Tournament reference if in tournament mode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='entertainment.quiztournament'),
        ),
        migrations.CreateModel(
            name='TournamentLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=255)),
                ('player_name', models.CharField(max_length=100)),
                ('best_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('best_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entertainment.quizsession')),
                ('tournament', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='entertainment.quiztournament')),
            ],
            options={
                'ordering': ['-best_score', 'updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['category', 'is_active'], name='entertainme_categor_a2c62b_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['question', 'is_correct'], name='entertainme_questio_6818ef_idx'),
        ),
        migrations.AddIndex(
            model_name='quizleaderboard',
            index=models.Index(fields=['quiz', '-best_score'], name='entertainme_quiz_id_6cc209_idx'),
        ),
        migrations.AddIndex(
            model_name='quizleaderboard',
            index=models.Index(fields=['session_token'], name='entertainme_session_f40d4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizleaderboard',
            unique_together={('quiz', 'session_token')},
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['session', 'answered_at'], name='entertainme_session_a45454_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['category', 'is_correct'], name='entertainme_categor_d02b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='quiztournament',
            index=models.Index(fields=['status', 'start_date'], name='entertainme_status_3d3ade_idx'),
        ),
        migrations.AddIndex(
            model_name='quiztournament',
            index=models.Index(fields=['slug'], name='entertainme_slug_c9f82c_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['session_token'], name='entertainme_session_3c9752_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['quiz', '-score'], name='entertainme_quiz_id_55d123_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['is_completed', '-started_at'], name='entertainme_is_comp_0ab0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['tournament', '-score'], name='entertainme_tournam_50ec8f_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentleaderboard',
            index=models.Index(fields=['tournament', '-best_score'], name='entertainme_tournam_adc72f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentleaderboard',
            unique_together={('tournament', 'session_token')},
        ),
    ]
