# Generated by Django 5.2.4 on 2025-11-14 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0008_quiz_quizcategory_quizquestion_quizanswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizPlayerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, help_text="Player's unique session token", max_length=255)),
                ('seen_question_ids', models.JSONField(default=dict, help_text='Dict of category_slug: [question_ids] player has seen')),
                ('seen_math_questions', models.JSONField(default=list, help_text='List of math questions player has seen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_progress', to='entertainment.quiz')),
            ],
            options={
                'indexes': [models.Index(fields=['session_token', 'quiz'], name='entertainme_session_44db70_idx')],
                'unique_together': {('session_token', 'quiz')},
            },
        ),
    ]
