# Generated by Django 5.2.4 on 2025-11-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0008_quizcategory_quiz_quizquestion_quizanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='consecutive_correct',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive correct answers for turbo mode multiplier'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='current_multiplier',
            field=models.PositiveIntegerField(default=1, help_text='Current score multiplier (doubles with each correct answer: 1x, 2x, 4x, 8x...)'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='multiplier_used',
            field=models.PositiveIntegerField(default=1, help_text='Multiplier that was active when this answer was submitted'),
        ),
    ]
