# Generated by Django 5.2.4 on 2025-11-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0009_quizsession_consecutive_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='is_practice_mode',
            field=models.BooleanField(default=False, help_text="If True, score won't appear on tournament leaderboard"),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='room_number',
            field=models.CharField(blank=True, help_text='Room number for tournament submissions (required for leaderboard)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='external_player_id',
            field=models.CharField(blank=True, help_text='Optional external player identifier (e.g., device ID)', max_length=100, null=True),
        ),
    ]
