# Generated by Django 5.2.4 on 2025-11-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0010_quizsession_is_practice_mode_quizsession_room_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='hotel_identifier',
            field=models.CharField(blank=True, help_text='Hotel identifier from QR code (optional for tournament tracking)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='hotel_identifier',
            field=models.CharField(blank=True, help_text='Hotel identifier from session (optional)', max_length=100, null=True),
        ),
    ]
