# Generated by Django 5.2.4 on 2025-11-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0011_alter_quizsession_hotel_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quizsession',
            name='entertainme_hotel_i_b4a5c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='quizsubmission',
            name='entertainme_hotel_i_0083e6_idx',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='hotel_identifier',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='is_practice_mode',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='quizsubmission',
            name='hotel_identifier',
        ),
    ]
