# Generated by Django 5.2.4 on 2025-11-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0012_remove_quizsession_entertainme_hotel_i_b4a5c8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='is_tournament',
            field=models.BooleanField(default=False, help_text='True for tournament mode, False for casual play'),
        ),
    ]
