# Generated by Django 5.2.4 on 2025-11-05 11:47

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0004_alter_hotel_logo'),
        ('staff', '0015_generate_qr_tokens_for_existing_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message content')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the message was sent')),
                ('is_read', models.BooleanField(default=False, help_text='Whether message has been read by recipients')),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('read_by', models.ManyToManyField(blank=True, help_text='Staff members who have read this message', related_name='read_staff_messages', to='staff.staff')),
                ('reply_to', models.ForeignKey(blank=True, help_text='Message this is replying to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='staff_chat.staffchatmessage')),
                ('sender', models.ForeignKey(help_text='Staff member who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_staff_messages', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Chat Message',
                'verbose_name_plural': 'Staff Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StaffChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='staff_chat_attachment')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('pdf', 'PDF'), ('other', 'Other')], default='other', max_length=20)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(help_text='Message this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='staff_chat.staffchatmessage')),
            ],
            options={
                'verbose_name': 'Staff Chat Attachment',
                'verbose_name_plural': 'Staff Chat Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional conversation title for group chats', max_length=255, null=True)),
                ('is_group', models.BooleanField(default=False, help_text='True if conversation has more than 2 participants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(help_text='Hotel this conversation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='staff_conversations', to='hotel.hotel')),
                ('participants', models.ManyToManyField(help_text='Staff members participating in this conversation', related_name='staff_conversations', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Conversation',
                'verbose_name_plural': 'Staff Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='staffchatmessage',
            name='conversation',
            field=models.ForeignKey(help_text='Conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='staff_chat.staffconversation'),
        ),
    ]
