# Generated by Django 5.2.4 on 2025-11-05 12:41

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_generate_qr_tokens_for_existing_codes'),
        ('staff_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffchatattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated thumbnail for images', null=True, upload_to='staff_chat_thumbnails/'),
        ),
        migrations.AddField(
            model_name='staffchatmessage',
            name='delivered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staffchatmessage',
            name='mentions',
            field=models.ManyToManyField(blank=True, help_text='Staff members mentioned in this message', related_name='mentioned_in_staff_messages', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='staffchatmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('read', 'Read')], default='delivered', max_length=20),
        ),
        migrations.AddField(
            model_name='staffconversation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffconversation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who created this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_conversations', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='staffconversation',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for group chats', null=True),
        ),
        migrations.AddField(
            model_name='staffconversation',
            name='group_avatar',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional avatar for group conversations', max_length=255, null=True, verbose_name='group_avatar'),
        ),
        migrations.AddField(
            model_name='staffconversation',
            name='has_unread',
            field=models.BooleanField(default=False, help_text='Quick flag to show if conversation has any unread messages'),
        ),
        migrations.AddField(
            model_name='staffconversation',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived conversations are hidden from main list'),
        ),
        migrations.AlterField(
            model_name='staffchatattachment',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffchatmessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='True when ALL participants have read the message'),
        ),
        migrations.CreateModel(
            name='StaffMessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('👍', 'Thumbs Up'), ('❤️', 'Heart'), ('😊', 'Smile'), ('😂', 'Laugh'), ('😮', 'Wow'), ('😢', 'Sad'), ('🎉', 'Party'), ('🔥', 'Fire'), ('✅', 'Check'), ('👏', 'Clap')], help_text='Emoji reaction', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(help_text='Message this reaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='staff_chat.staffchatmessage')),
                ('staff', models.ForeignKey(help_text='Staff member who reacted', on_delete=django.db.models.deletion.CASCADE, related_name='staff_message_reactions', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Message Reaction',
                'verbose_name_plural': 'Staff Message Reactions',
                'ordering': ['created_at'],
                'unique_together': {('message', 'staff', 'emoji')},
            },
        ),
    ]
