# Generated by Django 5.2.4 on 2025-11-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_generate_qr_tokens_for_existing_codes'),
        ('staff_chat', '0003_fix_has_unread_null_values'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffmessagereaction',
            unique_together={('message', 'staff')},
        ),
    ]
