# Generated by Django 5.2.1 on 2025-06-02 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantbooking',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='restaurantbooking',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='venuebooking',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='venuebooking',
            name='hotel',
        ),
        migrations.AlterModelOptions(
            name='bookingcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='bookingcategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Set this if it's a subcategory of another category", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='bookings.bookingcategory'),
        ),
        migrations.AlterField(
            model_name='bookingcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='PorterageBooking',
        ),
        migrations.DeleteModel(
            name='RestaurantBooking',
        ),
        migrations.DeleteModel(
            name='VenueBooking',
        ),
    ]
