# Generated by Django 5.2.1 on 2025-06-02 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_restaurantbooking_booking_and_more'),
        ('hotel', '0002_hotel_subdomain_alter_hotel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingcategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='bookingcategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='bookingcategory',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='hotel.hotel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BookingSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='hotel.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='bookingcategory',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='bookings.bookingsubcategory'),
            preserve_default=False,
        ),
    ]
