# Generated by Django 5.2.1 on 2025-06-02 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookingcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.PositiveIntegerField(default=0)),
                ('children', models.PositiveIntegerField(default=0)),
                ('infants', models.PositiveIntegerField(default=0)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.booking')),
            ],
        ),
    ]
