# Generated by Django 5.2.1 on 2025-06-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
    ]
