# Generated by Django 5.2.1 on 2025-06-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='total',
            field=models.PositiveIntegerField(default=1, help_text='Total number of seats to reserve for this booking'),
        ),
    ]
