# Generated by Django 5.2.1 on 2025-06-04 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_seats_total'),
        ('hotel', '0002_hotel_subdomain_alter_hotel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Slug used in URLs (e.g., strawberry-tree)', unique=True)),
                ('capacity', models.PositiveIntegerField(default=30, help_text='Max number of guests')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='hotel.hotel')),
            ],
        ),
    ]
