# Generated by Django 5.2.1 on 2025-06-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsubcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='subcategory',
            field=models.OneToOneField(blank=True, help_text='Optional link to BookingSubcategory for filtering bookings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant', to='bookings.bookingsubcategory'),
        ),
    ]
