# Generated by Django 5.2.1 on 2025-06-04 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_bookingsubcategory_slug_restaurant_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.restaurant'),
        ),
    ]
