# Generated by Django 5.2.4 on 2025-08-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
