# Generated by Django 5.2.4 on 2025-08-16 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_voucher_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x', models.PositiveIntegerField(default=0)),
                ('y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=200)),
                ('height', models.PositiveIntegerField(default=200)),
                ('z_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Human label like T12 / A3', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('shape', models.CharField(choices=[('RECT', 'Rectangle'), ('CIRCLE', 'Circle'), ('OVAL', 'Oval')], default='RECT', max_length=10)),
                ('x', models.PositiveIntegerField(default=0)),
                ('y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, help_text='For RECT/OVAL', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='For RECT/OVAL', null=True)),
                ('radius', models.PositiveIntegerField(blank=True, help_text='For CIRCLE', null=True)),
                ('rotation', models.IntegerField(default=0, help_text='Degrees, clockwise')),
                ('joinable', models.BooleanField(default=True, help_text='Can be combined with neighbors')),
                ('join_group', models.CharField(blank=True, help_text='Tables with the same value are combinable', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='bookings.blueprintarea')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='bookings.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_tables', to='bookings.booking')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_tables', to='bookings.diningtable')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(default=1000, help_text='Canvas width in px')),
                ('height', models.PositiveIntegerField(default=600, help_text='Canvas height in px')),
                ('grid_size', models.PositiveIntegerField(default=25, help_text='Snap-to grid size')),
                ('background_image', models.ImageField(blank=True, help_text='Optional background image of the floorplan', null=True, upload_to='blueprints/')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blueprint', to='bookings.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='blueprintarea',
            name='blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='bookings.restaurantblueprint'),
        ),
        migrations.CreateModel(
            name='TableSeatSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(help_text='Seat index starting at 1')),
                ('offset_x', models.IntegerField(default=0)),
                ('offset_y', models.IntegerField(default=0)),
                ('angle_degrees', models.IntegerField(default=0)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_spots', to='bookings.diningtable')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddIndex(
            model_name='diningtable',
            index=models.Index(fields=['restaurant', 'area', 'join_group'], name='bookings_di_restaur_1bb27e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diningtable',
            unique_together={('restaurant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='bookingtable',
            unique_together={('booking', 'table')},
        ),
        migrations.AlterUniqueTogether(
            name='blueprintarea',
            unique_together={('blueprint', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tableseatspot',
            unique_together={('table', 'index')},
        ),
    ]
