# Generated by Django 5.2.4 on 2025-08-16 11:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_blueprintarea_diningtable_bookingtable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantblueprint',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional background image of the floorplan', max_length=255, null=True, verbose_name='image'),
        ),
    ]
