# Generated by Django 5.2.4 on 2025-08-17 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_alter_restaurant_closing_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon name or URL for frontend', max_length=100)),
                ('default_width', models.PositiveIntegerField(default=50)),
                ('default_height', models.PositiveIntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='BlueprintObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('x', models.PositiveIntegerField(default=0)),
                ('y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=50)),
                ('height', models.PositiveIntegerField(default=50)),
                ('rotation', models.IntegerField(default=0)),
                ('z_index', models.IntegerField(default=0)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='bookings.restaurantblueprint')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objects', to='bookings.blueprintobjecttype')),
            ],
        ),
    ]
