# Generated by Django 5.2.4 on 2025-08-18 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_blueprintobjecttype_blueprintobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintobject',
            name='blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprint_objects', to='bookings.restaurantblueprint'),
        ),
        migrations.AlterField(
            model_name='blueprintobject',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objects_type', to='bookings.blueprintobjecttype'),
        ),
    ]
