# Generated by Django 5.2.4 on 2025-08-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_alter_blueprintobject_blueprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningtable',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diningtable',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
