# Generated by Django 5.2.4 on 2025-08-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_alter_diningtable_x_alter_diningtable_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintobject',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objects_type', to='bookings.blueprintobjecttype'),
        ),
    ]
