# Generated by Django 5.2.4 on 2025-08-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_remove_booking_time_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
