# Generated by Django 5.2.4 on 2025-08-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_booking_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='max_bookings_per_hour',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_group_size',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
