# Generated by Django 5.2.4 on 2025-08-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_restaurant_max_bookings_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='taking_bookings',
            field=models.BooleanField(default=True),
        ),
    ]
