# Generated by Django 5.2.4 on 2025-09-20 10:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_restaurant_taking_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
