# Generated by Django 5.2.4 on 2025-12-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsubcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(help_text='Slug used in URLs (e.g., strawberry-tree)'),
        ),
    ]
