# Generated by Django 5.2.4 on 2025-12-15 14:19

from django.db import migrations
from django.utils.text import slugify


def normalize_slugs_forward(apps, schema_editor):
    """
    Normalize slugs for Restaurant and BookingSubcategory models.
    Ensures per-hotel uniqueness with deterministic collision resolution.
    """
    Restaurant = apps.get_model('bookings', 'Restaurant')
    BookingSubcategory = apps.get_model('bookings', 'BookingSubcategory')
    
    for model in [Restaurant, BookingSubcategory]:
        # Process by hotel to ensure per-hotel uniqueness
        for hotel_id in model.objects.values_list('hotel_id', flat=True).distinct():
            used_slugs = set()
            updates = []
            
            # Deterministic ordering within each hotel
            objects = model.objects.filter(hotel_id=hotel_id).order_by('id')
            
            for obj in objects:
                # Generate base slug from name
                base_slug = slugify(obj.name) if obj.name else "item"
                if not base_slug:
                    base_slug = "item"
                
                final_slug = base_slug
                counter = 2
                
                # Handle collisions within hotel
                while final_slug in used_slugs:
                    final_slug = f"{base_slug}-{counter}"
                    counter += 1
                
                used_slugs.add(final_slug)
                
                # Only update if slug changed
                if obj.slug != final_slug:
                    obj.slug = final_slug
                    updates.append(obj)
            
            # Bulk update per hotel for performance
            if updates:
                model.objects.bulk_update(updates, ['slug'])


def normalize_slugs_reverse(apps, schema_editor):
    """
    Reverse migration - no-op since we don't want to lose normalized slugs.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_remove_global_slug_unique'),
    ]

    operations = [
        migrations.RunPython(normalize_slugs_forward, normalize_slugs_reverse),
    ]
