# Generated by Django 5.2.4 on 2025-12-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_normalize_hotel_slugs'),
        ('hotel', '0029_bookingguest_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookingsubcategory',
            constraint=models.UniqueConstraint(fields=('hotel', 'slug'), name='uniq_booking_subcategory_hotel_slug'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.UniqueConstraint(fields=('hotel', 'slug'), name='uniq_restaurant_hotel_slug'),
        ),
    ]
