# Generated by Django 5.2.4 on 2025-07-24 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0004_alter_hotel_logo'),
        ('staff', '0005_staff_has_registered_face'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('verified_by_face', models.BooleanField(default=True)),
                ('location_note', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_logs', to='hotel.hotel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='staff_faces/')),
                ('encoding', models.JSONField(help_text='128‑dim face descriptor (list of floats)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_faces', to='hotel.hotel')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_data', to='staff.staff')),
            ],
        ),
    ]
