# Generated by Django 5.2.4 on 2025-07-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffface',
            name='encoding',
        ),
    ]
