# Generated by Django 5.2.4 on 2025-07-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_staffface_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffface',
            name='encoding',
            field=models.JSONField(default=list, help_text='128‑dim face descriptor (list of floats)'),
        ),
    ]
