# Generated by Django 5.2.4 on 2025-07-24 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_staffface_encoding'),
        ('hotel', '0004_alter_hotel_logo'),
        ('staff', '0005_staff_has_registered_face'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clocklog',
            options={'ordering': ['-time_in']},
        ),
        migrations.AddField(
            model_name='clocklog',
            name='auto_clock_out',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RosterPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Week 29 Roster'", max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RosterRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('required_count', models.PositiveIntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='attendance.rosterperiod')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_night', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='StaffAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('shift_date', models.DateField()),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('shift_type', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night'), ('split', 'Split'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('is_split_shift', models.BooleanField(default=False)),
                ('is_night_shift', models.BooleanField(default=False)),
                ('expected_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rosters', to='staff.staff')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_rosters', to='hotel.hotel')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='attendance.rosterperiod')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='staff.staff')),
            ],
            options={
                'ordering': ['shift_date', 'shift_start'],
                'unique_together': {('staff', 'shift_date')},
            },
        ),
    ]
