# Generated by Django 5.2.4 on 2025-07-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_clocklog_options_clocklog_auto_clock_out_and_more'),
        ('staff', '0006_alter_staff_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffroster',
            unique_together={('staff', 'shift_date', 'shift_start')},
        ),
    ]
