# Generated by Django 5.2.4 on 2025-07-26 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_staffroster_unique_together'),
        ('hotel', '0004_alter_hotel_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#0d6efd', max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_locations', to='hotel.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='staffroster',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='attendance.shiftlocation'),
        ),
    ]
