# Generated by Django 5.2.4 on 2025-07-28 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_shiftlocation_staffroster_location'),
        ('staff', '0008_role_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterrequirement',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_requirements', to='staff.department'),
        ),
        migrations.AlterField(
            model_name='rosterrequirement',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_requirements', to='staff.role'),
        ),
        migrations.AlterField(
            model_name='staffroster',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_entries', to='staff.department'),
        ),
    ]
