# Generated by Django 5.2.4 on 2025-07-30 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_dailyplan_dailyplanentry'),
        ('staff', '0008_role_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplanentry',
            name='department',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.department'),
        ),
    ]
