# Generated by Django 5.2.4 on 2025-07-31 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_dailyplanentry_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplanentry',
            name='roster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_plan_entries', to='attendance.staffroster'),
        ),
    ]
