# Generated by Django 5.2.4 on 2025-07-31 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_dailyplanentry_roster'),
        ('staff', '0008_role_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyplanentry',
            unique_together={('plan', 'staff', 'location')},
        ),
    ]
