# Generated by Django 5.2.4 on 2025-07-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_dailyplanentry_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplanentry',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyplanentry',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
