# Generated by Django 5.2.4 on 2025-07-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_dailyplanentry_shift_end_dailyplanentry_shift_start'),
        ('staff', '0008_role_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyplanentry',
            unique_together={('plan', 'staff', 'location', 'shift_start', 'shift_end')},
        ),
    ]
