# Generated by Django 5.2.4 on 2025-08-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_dailyplanentry_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='clocklog',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
