# Generated by Django 5.2.4 on 2025-11-29 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_clocklog_hours_worked'),
        ('hotel', '0025_alter_preset_target_type'),
        ('staff', '0015_generate_qr_tokens_for_existing_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', 'Create Shift'), ('update', 'Update Shift'), ('delete', 'Delete Shift'), ('copy_bulk', 'Copy All Shifts (Period to Period)'), ('copy_day', 'Copy Day Shifts'), ('copy_staff', 'Copy Staff Shifts'), ('bulk_save', 'Bulk Save Operation')], max_length=20)),
                ('affected_shifts_count', models.PositiveIntegerField(default=0)),
                ('operation_details', models.JSONField(blank=True, default=dict, help_text='Additional operation metadata (source_date, target_date, etc.)')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('affected_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_modifications_audit', to='staff.staff')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_audit_logs', to='hotel.hotel')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
                ('roster_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='attendance.staffroster')),
                ('source_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_source', to='attendance.rosterperiod')),
                ('target_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_target', to='attendance.rosterperiod')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['hotel', 'operation_type'], name='attendance__hotel_i_8c56e5_idx'), models.Index(fields=['performed_by', 'timestamp'], name='attendance__perform_108502_idx'), models.Index(fields=['hotel', 'timestamp'], name='attendance__hotel_i_4ad8c8_idx')],
            },
        ),
    ]
