# Generated by Django 5.2.4 on 2025-11-30 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_rosterauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='clocklog',
            name='roster_shift',
            field=models.ForeignKey(blank=True, help_text='Optional link to planned roster shift for this log.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clock_logs', to='attendance.staffroster'),
        ),
    ]
