# Generated by Django 5.2.4 on 2025-11-30 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_add_roster_shift_to_clocklog'),
        ('staff', '0015_generate_qr_tokens_for_existing_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clocklog',
            name='break_warning_sent',
            field=models.BooleanField(default=False, help_text='Break reminder notification sent for this session'),
        ),
        migrations.AddField(
            model_name='clocklog',
            name='hard_limit_warning_sent',
            field=models.BooleanField(default=False, help_text='Hard limit warning notification sent for this session'),
        ),
        migrations.AddField(
            model_name='clocklog',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Whether this log is approved for payroll calculations'),
        ),
        migrations.AddField(
            model_name='clocklog',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='Whether this log was rejected by management'),
        ),
        migrations.AddField(
            model_name='clocklog',
            name='is_unrostered',
            field=models.BooleanField(default=False, help_text='True if clocked in without matching roster shift'),
        ),
        migrations.AddField(
            model_name='clocklog',
            name='long_session_ack_mode',
            field=models.CharField(blank=True, choices=[('stay', 'Stay clocked in'), ('clocked_out', 'Clocked out after warning')], help_text='How staff responded to hard limit warning', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clocklog',
            name='overtime_warning_sent',
            field=models.BooleanField(default=False, help_text='Overtime warning notification sent for this session'),
        ),
        migrations.AddField(
            model_name='rosterperiod',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='When this period was finalized', null=True),
        ),
        migrations.AddField(
            model_name='rosterperiod',
            name='finalized_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who finalized this period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_periods', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='rosterperiod',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='When finalized, related ClockLogs and StaffRoster shifts are locked'),
        ),
    ]
