# Generated by Django 5.2.4 on 2025-11-30 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_clocklog_break_warning_sent_and_more'),
        ('hotel', '0026_attendancesettings'),
        ('staff', '0015_generate_qr_tokens_for_existing_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('REGISTERED', 'Registered'), ('REVOKED', 'Revoked'), ('RE_REGISTERED', 'Re-registered')], help_text='Type of face lifecycle action performed', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the action (especially for revocation)', null=True)),
                ('consent_given', models.BooleanField(default=True, help_text='Whether consent was explicitly given for face data processing')),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the client when action was performed', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string for audit trail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_audit_logs', to='hotel.hotel')),
                ('performed_by', models.ForeignKey(blank=True, help_text='Staff member who performed this action (may be same as target staff for self-registration)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_face_actions', to='staff.staff')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_audit_logs', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Face Audit Log',
                'verbose_name_plural': 'Face Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
