# Generated by Django 5.2.4 on 2025-11-30 17:50

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_faceauditlog'),
        ('hotel', '0026_attendancesettings'),
        ('staff', '0015_generate_qr_tokens_for_existing_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffface',
            options={'ordering': ['-created_at'], 'verbose_name': 'Staff Face Data', 'verbose_name_plural': 'Staff Face Data'},
        ),
        migrations.AddField(
            model_name='staffface',
            name='consent_given',
            field=models.BooleanField(default=True, help_text='Whether staff member consented to face data collection'),
        ),
        migrations.AddField(
            model_name='staffface',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this face data is active for recognition'),
        ),
        migrations.AddField(
            model_name='staffface',
            name='registered_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who performed the registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_faces', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='staffface',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staffface',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Face image stored in Cloudinary cloud storage', max_length=255, null=True, verbose_name='face_image'),
        ),
        migrations.AddIndex(
            model_name='staffface',
            index=models.Index(fields=['hotel', 'is_active'], name='attendance__hotel_i_bf5b74_idx'),
        ),
        migrations.AddIndex(
            model_name='staffface',
            index=models.Index(fields=['staff', 'is_active'], name='attendance__staff_i_580cb1_idx'),
        ),
    ]
