# Generated by Django 5.2.4 on 2025-11-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_alter_staffface_options_staffface_consent_given_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clocklog',
            name='break_end',
            field=models.DateTimeField(blank=True, help_text='When break ended', null=True),
        ),
        migrations.AddField(
            model_name='clocklog',
            name='break_start',
            field=models.DateTimeField(blank=True, help_text='When break started', null=True),
        ),
        migrations.AddField(
            model_name='clocklog',
            name='is_on_break',
            field=models.BooleanField(default=False, help_text='Whether staff is currently on break'),
        ),
        migrations.AddField(
            model_name='clocklog',
            name='total_break_minutes',
            field=models.IntegerField(default=0, help_text='Total break time in minutes for this shift'),
        ),
    ]
