# Generated by Django 5.2.4 on 2025-11-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_add_break_functionality'),
    ]

    operations = [
        migrations.AddField(
            model_name='clocklog',
            name='is_kiosk_mode',
            field=models.BooleanField(default=False, help_text='True if clocked in via shared kiosk device (affects frontend behavior)'),
        ),
    ]
